### ISSUE TITLE
Paper format and journal

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#1]
The paper is envisaged as a description of msprime all of the features that it has, with comprehensive references to the literature of existing simulators, to emphasise msprime's large feature set and fragmented state of the simulation ecosystem.

Some options:

## Bioinformatics application note

A bioinformations [application note](https://academic.oup.com/bioinformatics/pages/instructions_for_authors) is a pretty standard format for software papers like this. It would be hard to argue against publishing this paper in Bioinformatics, given the number of simulators that are already published in this format.

The downside is the format is **very** short. My current, very incomplete, draft is already longer than this. Given the number of references and the number of authors, I think it would be very terse indeed.

## Heredity computer note

Heredity have recently launched a [computer note](https://www.nature.com/hdy/authors-and-referees/gta) format which might be appropriate.

**Comment by fbaumdicker** [comment]
Given the number of new features, Heredity sounds appropriate to me.

Other alternatives might be:

BMC Bioinformatics
Briefings in Bioinformatics
PLOS Computational Biology
GigaScience
Nucleic Acids Research

**Comment by andrewkern** [comment]
I'd also throw G3 into the mix. They are fully OA, very good to deal with, and generally a nice journal IMO

**Comment by molpopgen** [comment]
I second G3

**Comment by jeromekelleher** [comment]
Thanks for the input. I think we want to go somewhere where there's an explicit "software paper" stream. Do G3 have this?

**Comment by hugovk** [comment]
Another option is the Journal of Open Source Software, JOSS.

Here's an example submission:

* https://github.com/fatiando/pooch/pull/116
* https://github.com/openjournals/joss-reviews/issues/1928
* https://github.com/openjournals/joss-reviews/issues/1943
* https://joss.theoj.org/papers/10.21105/joss.01943

**Comment by jeromekelleher** [comment]
Good idea, thanks @hugovk. I think we'd probably weight more towards a biology journal to get the attention of potential users, but it's a good option.

**Comment by molpopgen** [comment]
> Thanks for the input. I think we want to go somewhere where there's an explicit "software paper" stream. Do G3 have this?

Yep. https://www.g3journal.org/content/article-types#software

**Comment by jeromekelleher** [comment]
OK, G3 it is for now. We can revisit later if needs be.

**Comment by sgravel** [comment]
I'll also suggest the Methods, Technology, and Resources section at Genetics. I think the manuscript could be a good fit there, and could always be forwarded with reviews to G3 if needed.  Even though it a delayed OA journal, there is an instant OA option as well.
