### ISSUE TITLE
Feature section: multiple merger coalescents

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#11]
We need a feature section for multiple merger coalescents. See #7 for an overview of feature section structures.

@JereKoskela, @TPPSellinger, @eldonb would one or more of you like to volunteer for this please?

**Comment by eldonb** [comment]
I'd be happy to contribute to this section

**Comment by jeromekelleher** [comment]
Great, thanks Bjarki.

**Comment by jeromekelleher** [comment]
Now that the multiple merger coalescents are officially done in msprime, this would be a great time to write up the feature section here while it's still fresh. We don't need much, just a few paragraphs (and presumably could refer to an "in progress" manuscript that's been around somewhere?)

**Comment by JereKoskela** [comment]
> Now that the multiple merger coalescents are officially done in msprime, this would be a great time to write up the feature section here while it's still fresh. We don't need much, just a few paragraphs (and presumably could refer to an "in progress" manuscript that's been around somewhere?)

I was thinking that too. @eldonb, if you haven't yet started on this, then I could probably put together an initial draft in fairly short order by using the documentation as a starting point. Let me know what you think.

**Comment by TPPSellinger** [comment]
Great ! Let me know if there is anything I can do to help.

**Comment by eldonb** [comment]
sorry for the delay - I promised to do this, so  I  will put together a draft;  I have texts anyway  ready  so I can almost just copy and paste -  
0) the "in progress" manuscript is still in progress, and is  in a way waiting for  another  "in progress"  manuscript, which I was hoping would turn into the original paper for the truncated Beta-coalescent,  but if we can simply  cite an "in progress" manuscript then I am happy
1) do we  want  to include  a  Xi-coalescent  from the Birkner, Liu, and Sturm  (2015) paper, it's a  Xi-coalescent allowing at most two simultaneous mergers  with  the  Xi-measure on  (x/4, x/4, 0, ...), where  x is a Beta(2-a,a) random variate, so is different from the four-fold Xi-coalescent  ?  Either way is fine with me 
2)  do you want to include  the  code for the  expected SFS  for the  multiple mergers  somehow within msprime ?   I would only be happy to see the code being useful;  I think I can also implement the expected SFS for the  two-fold Xi-coalescent

**Comment by jeromekelleher** [comment]
Excellent, thanks @eldonb! I don't think we want to add anything else to msprime 1.0 at this point, as there's a lot of things that need finishing up now. Looking forward to seeing the text for this section!

**Comment by eldonb** [comment]
a draft is attached,  hope you can read and/or download it:
[msprimepaper.pdf](https://github.com/tskit-dev/msprime-1.0-paper/files/4661932/msprimepaper.pdf)

I have not mentioned 
1.  the different scalings  of time and recombination, 
2. how we sample the processes

 but I wanted to  let you see the state of it -  comments  very welcome

**Comment by jeromekelleher** [comment]
Closed in #31.
