### ISSUE TITLE
GC section signoff

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#119]
I updated the GC section in #118 - can you read through this please @fbaumdicker and @hyanwong and sign off on it (or comment/make changes, as needed).

The figure should be done now apart from some visual tweaks.

**Comment by jeromekelleher** [comment]
Ping @fbaumdicker - any chance you could take a look through this section?

**Comment by fbaumdicker** [comment]
I just left a short comment in the already merged PR #118 .
Short summary: LGTM ;)
