### ISSUE TITLE
Feature section: simultaneous bottlenecks

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#12]
We need a feature section for simultaneous bottlenecks. See #7 for an overview of feature section structures.

This one's all yours @KLohse

**Comment by jeromekelleher** [comment]
More or less done now, closing in favour of #33.

**Comment by KLohse** [comment]
Thanks @jeromekelleher! I've checked the instantaneous bottelencks section, which is great! I am assuming that simultaneous bottelencks are redundant and no separate feature section is needed.

**Comment by jeromekelleher** [comment]
Yep, all done @KLohse! I'll be pinging you for comments on the full ms draft "soon" hopefully.
