### ISSUE TITLE
Author details

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#122]
Since the author list got added in #121, we need to get the affiliations and acknowledgements. Can each author check in the [tex file](https://github.com/tskit-dev/msprime-1.0-paper/blob/e01aa6677af7fc92fb6d97e7f58d84eae0c6a50a/paper.tex#L47)

- The spelling of their name
- Their position in the alphabetical list
- Their affiliation
- That they have acknowledged any appropriate grants in the [Acknowledgements](https://github.com/tskit-dev/msprime-1.0-paper/blob/e01aa6677af7fc92fb6d97e7f58d84eae0c6a50a/paper.tex#L1546)

We hope to submit the preprint in a week or so, so please do check these details ASAP.

**Comment by agladstein** [comment]
Can you add Embark in addition to UNC for me? Embark should be:
Embark Veterinary, Inc., Boston, Massachusetts, United States of America

**Comment by jeromekelleher** [comment]
Will do @agladstein - I'll put it in once things have quietened down a bit as I'll need to renumber things and I don't want to clash with in-progress edits.

**Comment by gregorgorjanc** [comment]
Affiliation: correct!

Acknowledgements: please use "Gregor Gorjanc is supported by the Chancellor's Fellowship of the University of Edinburgh and the BBSRC grant to The Roslin Institute BBS/E/D/30002275."

**Comment by jeromekelleher** [comment]
Done in #129 @gregorgorjanc

**Comment by nspope** [comment]
Thanks, @jeromekelleher.

Name: Nathaniel S. Pope
Affiliation: Department of Entomology, Pennsylvania State University, University Park, Pennsylvania, United States of America

**Comment by sgravel** [comment]
Name and affiliations are ok. 
Acknowledgements: 
"This research was undertaken, in part, thanks to funding from the Canada Research Chairs Program, from the Canadian Institutes of Health Research PJT 173300, and from the Canadian Foundation for Innovation."

**Comment by molpopgen** [comment]
My affiliation is slightly different:

University of California, Irvine, CA

The "at Irvine" is the issue.

**Comment by jeromekelleher** [comment]
@sgravel - I'm not sure your text will fit in well with the rest of the Acks. We probably want something in the form of "SG acknowledges funding from the Canada Research...". Is this OK with you, or is the above wording mandatory?

**Comment by sgravel** [comment]
The wording is the recommended language by the agency, but feel free to change if that suits the MS better. eg:
"SG achnowledges funding from the Canada Research Chairs Program, from the Canadian Institutes of Health Research PJT 173300, and from the Canadian Foundation for Innovation."

BTW, I noticed you had some collision of initials with JK in that section :)

**Comment by gbinux** [comment]
Thanks, @jeromekelleher.
Name: Bing Guo
Affiliation: Institute for Genome Sciences, University of Maryland School of Medicine, Baltimore, MD

**Comment by winni2k** [comment]
Thanks for including me on this paper @jeromekelleher and everyone else!
My affiliation should probably be: 
Center for Hematology and Regenerative Medicine, Karolinska Institute

**Comment by fbaumdicker** [comment]
My affiliation has somehow lost the most important part. It should ideally be:

Cluster of Excellence "Controlling Microbes to Fight Infections", Mathematical and Computational Population Genetics, University of Tübingen, Germany

If this is too long for the journal we could also drop the last part and use:
Cluster of Excellence "Controlling Microbes to Fight Infections", University of Tübingen, Germany

Can you change this back @jeromekelleher?

**Comment by jeromekelleher** [comment]
Sorry @fbaumdicker, my bad, I'll fix it.

**Comment by jeromekelleher** [comment]
@saunack and @castedo - do you have an affiliation you would like to use here?

**Comment by saunack** [comment]
Thanks for the reminder @jeromekelleher 
I'm not sure about my affiliation, since all my work was done before I received my college degree, but wasn't related to it in any way. Can you please advise me on what is the usual practice followed in these cases? If the college name is to be used, you can put in "IIT Bombay".
Also, my name is present in the correct position by lexical ordering, but is spelled incorrectly. Can you please change my last name to Saunack?

**Comment by petrelharp** [comment]
@saunack - I think you can put as affiliation anything you want in this case. IIT Bombay would make sense (since you were "there" at the time), but any current affiliation would also work. (you could even make one up! "Saunack's Advanced Institute of Advanced Theoretical Applications"!)

**Comment by castedo** [comment]
> ... @castedo - do you have an affiliation you would like to use here?

I don't think I have an affiliation that is informative here.

I like @petrelharp humorous idea, but something referencing this community, not me ... like "Tree Sequence Institute of Advanced Open Source Development" or something like that. But in the absence of inspirational humor, I'd think listing nothing for affiliation makes the most sense.

**Comment by jgallowa07** [comment]
@jeromekelleher  If there's enough space, could you add the following current affiliation for me?

"Division of Public Health Sciences, Fred Hutchinson Cancer Research Center, Seattle, WA 98102, USA"
