### ISSUE TITLE
Mutation illustration figure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#128]
Figure 2 currently looks like this:

![Screenshot from 2021-08-09 17-16-11](https://user-images.githubusercontent.com/2664569/128739271-48ff350c-e13a-410c-a09f-afde2473ec86.png)

We need to decide what to do with it. I think at the least we want to greatly reduce the number of samples.

@petrelharp, did you have some plans here?

I'm pretty lukewarm on the necessity of it, but happy to go with the consensus.

**Comment by petrelharp** [comment]
I don't have plans - I kinda like lots of samples, but don't have a strong opinion. It seems like we're not going with the "illustrate all the figures" idea, so I'm fine dropping it.

**Comment by jeromekelleher** [comment]
I'm not ruling out having lots of tree sequence examles along with the plots, but it's a lot of work that someone has to do to create figures that look good and will survive final typesetting (setting things out as subfigures in latex is a waste of time, the formatting always gets mangled in production) .If someone wants to volunteer to create a set of high-quality PDFs that include the plots and the tree sequence illustrations, then great. I'm not going to do this work though, as I don't think it's worth it.

So, unless someone volunteers to do the graphics work required to make Fig 2 look good in a couple of days, I'll remove it.

**Comment by gregorgorjanc** [comment]
Looking at this fig with fresh eyes I actually think it pretty much as good as it can get! @hyanwong did a great job and I suggest submit as it is!

**Comment by hyanwong** [comment]
I do think it helps showing the tree sequence with and without added mutations, and additionally showcases the tree drawing possibilities. If we like having a reasonable number of samples, we can perhaps drop the symbol size a little so that the tips don't clash (and maybe reduced the number of tips too). I'm happy to have a quick go at this. 

Re formatting, is this simply a question of setting the two tree sequences side-by-side and adding an (a) and (b) label? If so, I can easily create code to do that, because you can nest SVGs within other SVGs, e.g.

```
import msprime
from IPython.display import HTML

ts =  msprime.sim_ancestry(8, recombination_rate=0.00005, sequence_length=1000, random_seed=1234)
ts_mut = msprime.sim_mutations(ts, rate=0.001)

width=800
height=300
top=40

SVG(
    f'<svg baseProfile="full" height="{height+top}" version="1.1" width="{width}" '
    'xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink">'
    + f'<g transform="translate(0 {top})"><text x="2" y="-10" font-size="20">a</text>'
    + ts.draw_svg(node_labels={}, size=(width/2, height)) + '</g>'
    + f'<g transform="translate({width/2} {top})"><text x="2" y="-10" font-size="20">b</text>'
    + ts_mut.draw_svg(node_labels={}, size=(width/2, height)) + '</g>'
    + "</svg>"
)
```

<img width="607" alt="Screenshot 2021-08-10 at 22 46 05" src="https://user-images.githubusercontent.com/4699014/128939295-914cf73b-5016-4652-b968-a1aaab99123e.png">

**Comment by fbaumdicker** [comment]
I would vote for even fewer samples. What about 4 diploids, i.e. 8 haploids? That would still illustrate the concepts and would be easier to grasp. The labels on the mutations could be "ACTG" as in @jeromekelleher s version above or the numbers shown in the version of @hyanwong . In my opinion, in the second case, the order of the mutations might confuse the reader.
What do you think about using the genome position of the mutations as labels, instead?

**Comment by hyanwong** [comment]
@fbaumdicker - I didn't try too hard to make it pretty. Personally, I think ATGC on the labels would be better: I just didn't code it up.

How's the placement of the (a) and (b), and to they e.g. need braces around them, or a dot afterwards?

**Comment by jeromekelleher** [comment]
I was going to make a pass at this today @hyanwong, based on your code above. Are you actively working on it? (I thought you were on holiday?)

**Comment by jeromekelleher** [comment]
Also, not wedded to this particular example - if someone wants to play around and find a more interesting one, go for it.

**Comment by gregorgorjanc** [comment]
Colouring nodes by an individual would be interesting since diploidy is mentioned in the text.

**Comment by petrelharp** [comment]
Looks great!

**Comment by hyanwong** [comment]
> I was going to make a pass at this today @hyanwong, based on your code above. Are you actively working on it? (I thought you were on holiday?)

Yeah, sorry - I'm intermittently checking emails between cream teas. I think 4 tips is a bit too few - I would perhaps vote for 8 (as @fbaumdicker pointed out, 4 diploids). Here's an example with a relatively nice pair of trees and mutations:

```
def mutated_tree():
    """
    Make a figure with (a) a tree and (b) some mutations added to it.
    """
    ts = msprime.sim_ancestry(
        4,
        population_size=1e4,
        recombination_rate=1e-8,
        sequence_length=1000,
        random_seed=142,
    )

    model = msprime.F84(kappa=2)
    mts = msprime.sim_mutations(ts, rate=1e-7, model=model, random_seed=21)
```

I've labelled the individuals as @gregorgorjanc suggested, using letters to avoid getting mixed up with node numbers, but perhaps as he says, colours would be better (and therefore, maybe 3 diploids, e.g. red, green, and blue?)

![mutated_tree](https://user-images.githubusercontent.com/4699014/129273441-d1e0f7c7-7c2c-47a7-a032-cef4690214dc.png)

**Comment by hyanwong** [comment]
> perhaps as he says, colours would be better (and therefore, maybe 3 diploids, e.g. red, green, and blue?)

Here's how that might look:

![mutated_tree](https://user-images.githubusercontent.com/4699014/129274581-44ea78d4-cb89-4af1-9f29-d0d333a4417e.png)

```
    ts = msprime.sim_ancestry(
        3,
        population_size=1e4,
        recombination_rate=1e-8,
        sequence_length=1000,
        random_seed=96,
    )

    model = msprime.F84(kappa=2)
    mts = msprime.sim_mutations(ts, rate=1e-7, model=model, random_seed=4)
```

**Comment by jeromekelleher** [comment]
Here's what the figure currently looks like:

![Screenshot from 2021-08-13 11-23-26](https://user-images.githubusercontent.com/2664569/129343473-7420efae-0bc3-46cc-b35c-10747ed5c224.png)

Do we like the limited parameters? We can't include all the params, or it'll be too long. We can explain in the caption that we've omitted most of the paramters?

**Comment by gregorgorjanc** [comment]
LGTM with G being Great!

**Comment by hyanwong** [comment]
I like the limited params. An extra option is to use the named param version: samples=3, for clarity, but I don't think we do this in the docs, so probably best to be consistent?

I think in the caption, we need to explain that the sample node colours have been tweaked to show individuals, though.

**Comment by jeromekelleher** [comment]
I don't think we need to worry about consistency with the docs, what every has the greatest clarity here. However, we should also used named parameters in the ``sim_mutations`` case then, which I think would be clumsy.

**Comment by hyanwong** [comment]
Yes, I agree: just thought I should mention the option.

**Comment by jeromekelleher** [comment]
Done in #158
