### ISSUE TITLE
Performance figure - is Ne*L correct?

### ISSUE THREAD

**Issue by gregorgorjanc** [tskit-dev/msprime-1.0-paper#139]
@petrelharp @jeromekelleher I am looking at the performance figure https://github.com/tskit-dev/msprime-1.0-paper/blob/main/figures/ancestry-perf.pdf and I wonder how do we get the vertical line for Homo Sapiens at 25K? If say Ne is 10K and L is ~30, then Ne * L would be 10K*30 = 300K, but the vertical line is at 25K (one order of magnitude off)?

**Comment by gregorgorjanc** [comment]
Ah, just chromosome 1 - all good then.

**Comment by jeromekelleher** [comment]
We consider it chromosome-by-chromosome, as there's no point in simulating multiple chromosomes simultaneously using the coalescent - see the [documentation](https://tskit.dev/msprime/docs/latest/ancestry.html#multiple-chromosomes) for more discussion on this point.
