### ISSUE TITLE
Finalise recombination perf figure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#150]
@petrelharp, what do you think of the current version of the recombination perf figure? Do you want to make some tweaks, or can we fix up the right hand panel x axis labels and be done?

**Comment by petrelharp** [comment]
It looks good to me - I don't even see what needs to be done with the x-axis labels.

More generally, though, I'd still vote for removing the `[width=\textwidth]` from the latex and producing figures that are the output size we want, so the fonts aren't so small in the figures - this applies to all of them, though. And, I'm happy to do this.

**Comment by petrelharp** [comment]
LMK if you want me to deal with the x-axis labels.
