### ISSUE TITLE
Finalise ARG illustration figure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#151]
Here's what the ARG illustration figure currently looks like:

![Screenshot from 2021-08-12 14-32-11](https://user-images.githubusercontent.com/2664569/129205723-f57c79d1-85a0-4b4f-ba1c-e144a3460c1d.png)

It would be good if the three panels had a common y axis, so that the nodes had the same height in each one.

Also would be nice if the (A), (B), (C) labels could be on top, for concistency with other figures.

**Comment by jeromekelleher** [comment]
@gtsambos - do you have a sense of how much trouble this would be? If it's a lot of hassle it could be simpler for me to hack something together with SVG like we did for the mutations plot (should be pretty easy to reproduce (A) it's just a few lines)

**Comment by gtsambos** [comment]
Both should be pretty easy -- I'll do it this afternoon 🙂
