### ISSUE TITLE
Standarise colours to matplotlib palette?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#159]
I quite like having a set palette of colours - would it be OK to update the tree sequence example figure to use the standard matplotlib palette @petrelharp?

**Comment by petrelharp** [comment]
please do!

**Comment by petrelharp** [comment]
colors in matplotlib is something I have not come to terms with yet.

**Comment by jeromekelleher** [comment]
Done in #158
