### ISSUE TITLE
Feature section: ground truth for N(t) methods and where are lineages

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#16]
As part of the stdpopsim work, we added some very nifty features for computing ground truth values and related functions for computing the location of lineages over time. We should add a features section (see #7 for what this means) describing this.

@petrelharp, @apragsdale, you're the main people involved here; any thoughts?

**Comment by apragsdale** [comment]
Hey @jeromekelleher, I'd be happy to draft up a paragraph or two describing what we did here. I'll give this repo a read through and suggest something here that will cover it. I'm assuming it's not too urgent, but I'll try to get to this soon while it's fresh in our minds, like you said.

**Comment by jeromekelleher** [comment]
Great, thanks @apragsdale. Doesn't have to be particularly polished, just get the relevant information and citations in and we can refine later.
