### ISSUE TITLE
Haldane's sieve reference

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#162]
Actually, now that I think about it, I don't get the Haldane's sieve reference in the discussion. What's the connection to dominant and recessive alleles @petrelharp?

> This is unsurprising, since the majority of simulation software development is performed by students, who are themselves learning to code, often without formal training in software development. Although this “Haldane’s sieve” of software has produced many good tools and enabled decades of research, it also represents a missed opportunity to invest as a community in shared infrastructure and mentorship in good software development practice.

**Comment by petrelharp** [comment]
Darn it, I thought that might have been clever. It doesn't have to do with dominant/recessive, you're right - I was drawing the analogy to lots of new mutatations, with maybe some of the good ones surviving (but, stochastically). It's probably not a good analogy, thinking harder on it.

**Comment by jeromekelleher** [comment]
@petrelharp, any thoughts on this? This is basically the last thing left to fix in the text I think.

**Comment by petrelharp** [comment]
I'll fix it up. Note that I'm using in the same way as https://haldanessieve.org/about/ (see at the bottom).
