### ISSUE TITLE
a few small comments

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime-1.0-paper#166]
Thanks Jerome - 
a few  very minor comments below;   and  I would maybe like to go once more over it 

 use line numbers - put
\usepackage[right]{lineno}
in preamble, and then
\linenumbers
where they should start, e.g. before Introduction;
I think this will help the reviewers

the line numbers  below refer to the line numbers for paper.tex on github :

156: Stochastic simulation is a key tool in population genetics.
The models involved are often analytically intractable, and simulation is then
the only way of evaluating a given inference.

184: The coalescent process (maybe refer here also to the papers by Kingman from 1982, who formally derived
the coalescent; I think Hudson did so only informally)

@article{K82,
        author = {J F C Kingman},
        journal = {Stoch Proc Appl},
        pages = {235--248},
        title = {The coalescent},
        volume = 13,
        year = 1982
}

@article{K82b,
        author = {J F C Kingman},
        journal = {J App Probab},
        pages = {27--43},
        title = {On the genealogy of large populations},
        volume = {{19A}},
        year = 1982
}

406: Let us define a `genome' as the chromosome ...

I usually think of a `genome' as all the chromosomes of a diploid (or polyploid) individual, so
maybe for sake of illustration  simply talk about `chromosomes' ?

654: could we explain what we mean by a `mature' code ?

line 1169: include a reference to Schweinsberg (2003), where the Beta-coalescent is first mentioned

@article{schweinsberg03,
        author = {J Schweinsberg},
        journal = {Stoch Proc Appl},
        pages = {107--139},
        title = {Coalescent processes obtained from supercritical {G}alton-{W}atson processes},
        volume = 106,
        year = 2003
}

line 1174: include a reference to Birkner etal where the Dirac-coalescent is first mentioned:

@article{BBE13,
        author = {M Birkner and J Blath and B Eldon},
        journal = {Genetics},
        pages = {255--290},
        title = {An ancestral recombination graph for diploid populations with skewed offspring distribution},
        volume = 193,
        year = 2013
}

1188:  `as a representation of the coalescent with recombination as a graph'

1713: the  `Appendix' indicating the start of Appendix  does not appear

2046: should it be \tan in the equation for \mu(p)
in the Selective sweeps trajectories ?

**Comment by jeromekelleher** [comment]
Thanks for this @eldonb, these are really helpful comments. I've implemented most of them as part of #169. Here are some responses to things I didn't agree with:

> 156: Stochastic simulation is a key tool in population genetics. The models involved are often analytically intractable, and simulation is then the only way of evaluating a given inference.

I think your version makes it seem like evaluating inferences is the *only* application of simulations, but there's a whole bunch more.

> 406: Let us define a `genome' as the chromosome ...

We had a long discussion about this in #304, and ended up with genome as the least-bad option. Chromosome has the disadvantage that it's not clear if you're talking about one or both strands of a chromosome.

> 654: could we explain what we mean by a `mature' code ?

I guess we're talking about a mature *interface*, which means it's been around a long time and isn't going to change in the future. For the context you pointed out though, I just deleted the word as it wasn't necessary.

> 1188: `as a representation of the coalescent with recombination as a graph'

I think it's important to keep the "stochastic process" bit here, even if it is redundant and clumsy. There's so much confusion around the topic that I'd prefer to be absolutely explicit here.

> 2046: should it be \tan in the equation for \mu(p)  in the Selective sweeps trajectories ?

Very well spotted! I've opened #170 to track this issue.
