### ISSUE TITLE
Some more details

### ISSUE THREAD

**Issue by mmatschiner** [tskit-dev/msprime-1.0-paper#168]
Finding anything wrong with this manuscript is really hard, it's excellently written.

But here are four details that could be addressed:
1) In the sentence "For example, ms has been forked to output information about migrating segments (Rosenzweig et al., 2016), ancestral lineages (Chen and Chen, 2013), and ms’s fork msHOT (Hellenthal and Stephens, 2007), has in turn been forked to output information on local ancestry (Racimo et al., 2017).", the comma before "has in turn been" should probably be removed.
2) In the legend of Figure 3, "and recombination rate of 10-8" could be removed because apparently three different recombination rates were used. It might be worth specifying "recombination rate" instead of just "rate" in the inset.
3) In the sentence "Taking a typical chromosome to be 1 Morgan in length, these plots show, roughly, that simulating chromosome-length samples from a population of thousands of individuals takes seconds, while samples from a population of tens of thousands takes minutes.", the last "takes" should be replaced with "take".
4) In the sentence "However, the generation-by- generation approach of the DTWF is less efficient than the coalescent with recombination when the number of lineages is significantly less than the population size (the regime where the coalescent is an accurate approximation), which usually happens in the quite recent past Bhaskar et al. (2014).", the opening parenthesis of the Bhaskar et al. reference is misplaced.

**Comment by jeromekelleher** [comment]
Thanks very much @mmatschiner, this is excellent. I've applied your comments. (2) is actually correct, because it's different *mutation* rates we're using, but I've clarified by using "mutation rate" in the legend.
