### ISSUE TITLE
Feature section: mutation models

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#17]
We need a section describing the general mutation models in msprime. If we get the SLiM mutation model implemented we should also discuss this (@petrelharp)

Should cite: 

- Seq-Gen
- [PyVolve](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4580465/)

Any others?

@GertjanBisschop and @petrelharp, you seem like the right people to take on this section?

See #7 for detail on what a feature section should look like.

**Comment by jeromekelleher** [comment]
@GertjanBisschop, fancy taking a quick pass at this while the mutation models are fresh in your head? (Can skip the stuff about the SLiM mtuation model, or just put in a TODO for it)

**Comment by jeromekelleher** [comment]
I made a first pass at this in #27. I made a start at doing a performance analysis, but it's very frustrating. Basically, even telling if we're simulating more or less the same model is quite hard because nobody tells you how many mutations have been generated (not even pyvolve, which is a Python API). We can fall back on the excellent work that @GertjanBisschop did to compare the outputs of pyvolve and SeqGen, but they are so much slower that I'm not sure it's worth the bother. We can't run SeqGen without outputting the full alignment, which will dominate for large sample sizes. I'm not sure how to quantify the run-times here.

[Phastsim](https://www.biorxiv.org/content/10.1101/2021.02.16.431497v1) is also somewhat frustrating, and I haven't been able to figure out how to run it in a way that's comparable with one of our simulations.

So, the question is, given that we can generate 200K mutations on a million sample tree and write out the results in less than 2 seconds, is there any actual point in doing a systematic comparison? This is Fast Enough for the vast majority of applications, surely.

(And that's not even making the point that this is on a tree *sequence*, which of course nothing else will get remotely near, given that they'd have to go through newick, tree-by-tree)

Anyhow, remaining to be done in this section:

- [ ] Finalise the performance comparison (see discussion immediately above)
- [ ] Outline the algorithm use to generate mutations (1 paragraph)
- [ ] Emphasise the point that we're fast on a single tree, but much faster on a tree sequence than anything else could possibly be because we work edge-by-edge rather than tree-by-tree

**Comment by JereKoskela** [comment]
It sounds like a meaningful benchmark could be generating and writing 200K random numbers to file. That must be an upper bound on the efficiency of any method, and it sounds like msprime is pretty close.

**Comment by molpopgen** [comment]
Another way to look at it is to ask questions about the entire workflow. It's not much used to generate mutations extremely quickly if it takes forever to analyze them, So you may consider the relevant body of work to be something like generating them and then counting their frequencies. That way, if you have to deal with an alignment, that just is what it is for that piece of software.

**Comment by jeromekelleher** [comment]
Closing, we have a draft with a good narrative around this now.
