### ISSUE TITLE
Cosmetic suggestions for fig 3

### ISSUE THREAD

**Issue by sgravel** [tskit-dev/msprime-1.0-paper#171]
Figure 3 suggestion: I would spell out "Mutation rate" as a title to the legend to avoid redundancy and make the graph more visually self-contained. 
I would also consider flipping the order of the items in the legend to have same sorting as in the data.

**Comment by sgravel** [comment]
Other minor cosmetic note: Figure 7A has a bit of overlap between label and the right frame.

**Comment by jeromekelleher** [comment]
Good call on 3, this is being done in #169 

For 7A, do you mean the "4 seconds" label? I guess shift the label leftwards so that it's right-aligned with the data point? (Like the other one)

**Comment by sgravel** [comment]
Yes, exactly. Right align would likely solve this indeed.
