### ISSUE TITLE
Confusing sentence in mutation appendix

### ISSUE THREAD

**Issue by sgravel** [tskit-dev/msprime-1.0-paper#173]
l.1737:
`If an edge spans a region of the genome with more than one mutation rate,
this is done separately for each distinct region.`

We use "region" twice in this sentence for two different things. I think we mean either: 

`If an edge spans regions of the genome with distinct mutation rates,
this is done separately for each distinct region.`

Or, more likely, 
 
`If an edge spans a region of the genome with more than one mutation rate,
this is done separately for each mutation rate.`

Perhaps it would be more clear to give an example of what multiple rates might refer to: 

`If an edge spans a region of the genome with more than one mutation rate, as may happen if we model multiple mutational processes, this is done separately for each mutation rate.`

**Comment by jeromekelleher** [comment]
I think it's correct as written, but clearly not clear enough. Suppose we have an edge spanning the genomic interval [l, r), and suppose we have two different mutation rates, mu_1 over [l, x) and mu_2 over [x, r). Then, we generate mutations separately on the intervals [l, x) and [x, r) at rates mu_1 and mu_2, respectively.

Does this clear it up for you @sgravel?

**Comment by sgravel** [comment]
That makes sense, but I think the sentence is confusing because the "region" in the first part and second part of the sentence refers to different things, and we refer to different mutation "rates" in the first part and to "regions" in the second without an explicit link between the two. So my brain really wants to identify the `regions` in the two parts of the sentence, which is not correct.. 

I would write e.g.:
`If an edge spans a section of the genome comprising multiple mutation regions, this is done separately for each region.`
