### ISSUE TITLE
Double checking likelihood definition. 

### ISSUE THREAD

**Issue by sgravel** [tskit-dev/msprime-1.0-paper#174]
In the following (l.1854), we may consider providing a citation, e.g., Kuhner et al. equation 1, https://www.genetics.org/content/156/3/1393.

The equation in the manuscript provided adds the variable $g_i$ in the discrete case. The definition of $g_i$ does not quite make sense to me though, but I may just be confused. 
According to the definition, $g_i$ is "the length of material in which the recombination at the end of the ith period *could* have taken place *without* affecting the resulting genealogy." The word "without" seems to indicate that this is the complement of l_i, that is, the irrelevant material. Further, the use of "could" suggests that this is a length that does not depend on where the recombination happened. But then the next sentence is "A recombination in ancestral material will always have gi = 1, while a recombination in trapped non-ancestral material can result in other values of g_i."

So I don't understand what g_i represents, but I may just be completely confused. 

```
Specifically, the function returns the logarithm of
\begin{equation*}
\Bigg( \frac{ 1 }{ 2 N } \Bigg)^{ q_c } \Bigg( \prod_{ i : \mathcal{R} } r g_i \Bigg)
	\exp\Bigg( -\sum_{ i = 1 }^q \Big[\frac{ 1 }{ 2 N } \binom{ k_i }{ 2 }
		+ r l_i \Big] t_i  \Bigg),
\end{equation*}
where $t_i$ is the number of generations between the $(i - 1)$th and $i$th event,
$k_i$ is the number of extant ancestors in that interval, $l_i$ is the number of links
in that interval that would split ancestral material should they recombine,
$q$ is the total number of events in the tree sequence $\texttt{ts}$,
$q_c$ is the number of coalescences, $\mathcal{R}$ is the set of indices
of time intervals which end in a recombination, and $g_i$ is the corresponding
\emph{gap}:  the length of material in which the recombination at the end of the
$i$th period could have taken place without affecting the resulting genealogy.
```

**Comment by JereKoskela** [comment]
Whether you're confused or not @sgravel, it clearly needs clarification. Is this any clearer?

...and $g_i$ is the corresponding \emph{gap}: one plus the length of contiguous non-ancestral material on either side of the link at which the recombination in question took place. The gap indicates the number of links (or length of genome in a continuous model) at which a recombination would result in the exactly the observed pattern of ancestral material in the ARG. For a continuous model of the genome and a recombination in ancestral material, we set $g_i = 1$ and interpret the result as a density.

**Comment by sgravel** [comment]
Ah yes, this makes much more sense! And now that I read this, I can parse the original sentence correctly :) You have an extra "the" in the edit you proposed, but otherwise excellent! Thanks!

...and $g_i$ is the corresponding \emph{gap}: one plus the length of contiguous non-ancestral material on either side of the link at which the recombination in question took place. The gap indicates the number of links (or length of genome in a continuous model) at which a recombination would result in exactly the observed pattern of ancestral material in the ARG. For a continuous model of the genome and a recombination in ancestral material, we set $g_i = 1$ and interpret the result as a density.

**Comment by JereKoskela** [comment]
Thanks! I'll clean up the edit and add a citation to Kuhner et al in a PR.

**Comment by jeromekelleher** [comment]
That'd be great, thanks @JereKoskela
