### ISSUE TITLE
only some very very small comments

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime-1.0-paper#181]
the line numbers refer to  the latest pdf version  

 comments 0:
line 610:  `nuetral'

 comment 1:
regarding Instantaneous bottlenecks:

the paper referenced below derive a Xi-coalescent, a simultaneous multiple-merger coalescent, for a  Wright-Fisher population
undergoing  strong instantaneous  bottlenecks  (see Prop 6.3);  so it could be referenced  along with  the other papers on this, 
but  I don"t think  their actual  Xi-coalescent has been implemented  

@article{BBMST09,
	author = {M Birkner and J Blath and M M\"{o}hle and M Steinr\"{u}cken and J Tams},
	journal = {ALEA Lat. Am. J. Probab. Math. Stat.},
	pages = {25--61},
	title = {A modified lookdown construction for the {X}i-{F}leming-{V}iot process with mutation and populations with recurrent bottlenecks},
	volume = 6,
	year = 2009
}

comment 2:
In Eq (2) for the Lambda-coal rate, we should explain the  `\one' symbol (for the case k=2) :   
line 1285: "where  \one{A} := 1  if A holds, and zero otherwise"

and some minor typos in the references, mainly just  raising some letters to the capital state:

in References line 762:
`{DNA} variation  in the high-fecundity {Atlantic} cod: '

the rreference on line 1012 looks a bit strange

reference line 1021:  {SARS-COV-2} 

reference line 1031:  {X}

reference line 1051:  {R}

reference line 1054: {Hudsons}

reference line 1104: {II}

reference page 1161: {Kingman's}

**Comment by jeromekelleher** [comment]
All done @eldonb, thanks very much for such a thorough reading!

As a side note, the \one macro clearly shows you're not a computer scientist - the [Iversonian brackets](https://en.wikipedia.org/wiki/Iverson_bracket) notation is so much nicer :wink:

Regarding the second Martin et al reference (line 1012 reference above), this is an erratum, and I agree it looks weird. This seems to be the actual reference though, so I didn't want to start chopping it up.
