### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by awohns** [tskit-dev/msprime-1.0-paper#182]
- [x] In addition to my affiliation with the Big Data Institute, please add: ```\affil[]{Broad Institute of MIT and Harvard}```. I'm not sure if "Cambridge, USA" should be included, it seems that most listed affiliations don't have a place associated with them.
- [x] On page 7, the citation ```(Thornton, 2014)``` goes over the margin. 
- [x] Typo: "nuetral" -> "neutral" in the Selective Sweeps section
- [x] Typo: "throughly" -> "thoroughly" in discussion

**Comment by jeromekelleher** [comment]
Re the addresses @awohns - I chopped out the bits that seems unnecessary. If someone wants to write you a letter, then I'm sure that they can figure out where the Broad institute is.
