### ISSUE TITLE
Paper figures still require chromium

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime-1.0-paper#188]
I just checkout out upstream/main and did `make`, and got 

```
python3 pretty_pictures.py mutated-tree
['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
# Have to use Chromium here because we use svg2. Hopefully
# we'll fix this soon and we'll be able to use simpler
# conversion tools, or convert directly within the
# generating script.
chromium --headless --no-margins --print-to-pdf=illustrations/mutated_tree.pdf illustrations/mutated_tree.svg
```

I thought that https://github.com/tskit-dev/tskit/pull/1626 meant that we didn't need to use chromium any more? But perhaps the paper is using the stable version of tskit, which doesn't have that fix? Just thought it was worth mentioning as ISTR there were font problems using chromium.

**Comment by jeromekelleher** [comment]
AFAIK, we still need chromium to get the margins right. I don't think it's worth updating at this point, I might take a look again when doing the final publication figures.

**Comment by hyanwong** [comment]
> AFAIK, we still need chromium to get the margins right. I don't think it's worth updating at this point, I might take a look again when doing the final publication figures.

Let me know if I can help.
