### ISSUE TITLE
Discuss historical injustice to women in popgen computing

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#193]
one comment here-- i think it would be fitting to include this reference (https://doi.org/10.1534/genetics.118.301277) which highlights the ways in which the contributions of women to population genetics have been minimized through history

See changes merged in #192 for background

_Originally posted by @andrewkern in https://github.com/tskit-dev/msprime-1.0-paper/pull/192#discussion_r706346917_

**Comment by jeromekelleher** [comment]
I think a good introduction to our paragraph on acknowledging our gender skew would be to start with a sentence citing the above paper. Something like

> Women played a central role in the early development of computational population genetics, but their contributions were marginalised [cite paper]. While [things aren't quite this bad any more], it is important to acknowledge that...

What do we think?

**Comment by agladstein** [comment]
Sounds good to me

**Comment by petrelharp** [comment]
Also sounds good to me, although I don't think we need to say the "things are quite this bad any more" bit.

**Comment by jeromekelleher** [comment]
Sure, this is a very crude first pass, just trying to get the basic idea for comments

**Comment by andrewkern** [comment]
Agreed, sounds good.
