### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#2]
Anyone who has contributed significantly to msprime will be an author on the paper describing the simulator (see #1 for discussion on journal/format). An author is someone who has contributed to the code, documentation, packaging or algorithm development. Minor doc fixes don't qualify (but this is a proposal, so if you don't agree please shout out).  

Note that we're not currently including contributions to code that is now part of [tskit](https://github.com/tskit-dev/tskit). Such contributions will be acknowledged in a planned tskit paper at some point in the future when tskit has accumulated lots of features.

Here is the current proposal, mainly based on the [contributions](https://github.com/tskit-dev/msprime/graphs/contributors) github page:

Ashander, Jaime, @ashander
Baumdicker, Franz, @fbaumdicker
Bisschop, Gertjan, @GertjanBisschop
Eldon, Bjarki, @eldonb
Ellerman, E. Castedo, @castedo
Galloway, Jared, @jgallowa07
Gladstein, Ariella, @agladstein
Goldstein, Daniel, @daniel-goldstein
Gorjanc, Gregor, @gregorgorjanc
Gower, Graham, @grahamgower
Gravel, Simon, @sgravel
Guo, Bing, @gbinux
Jeffery, Ben, @benjeffery 
Kelleher, Jerome, @jeromekelleher
Kern, Andrew, @andrewkern
Koskela, Jere, @JereKoskela
Kretzschmar, Warren W., @winni2k
Krukov, Ivan, @ivan-krukov
Lohse, Konrad, @KLohse
Matschiner, Michael, @mmatschiner
Nelson, Dominic, @DomNelson
Pope,  Nathaniel, @nspope
Quinto-Cortés, Consuelo  D., @cdquinto  
Ragsdale, Aaron, @apragsdale
Ralph, Peter, @petrelharp
Rodrigues, Murillo, F.  @mufernando
Saunack, Kumar, @saunack 
Sellinger, Thibaut, @TPPSellinger
Thornton, Kevin, @molpopgen
Tsambos, Georgia, @gtsambos
Van Kemenade, Hugo, @hugovk
Wohns, Anthony W, @awohns 
Wong, Yan, @hyanwong 
Zhu, Sha, @shajoezhu

If you do not wish to be an author, please let me know and I will remove you from the list. Otherwise, please click on the "Watch" button above to follow updates on this repo.

## Author order

~All authors will be listed in alphabetical order of surname, as this seems like the least unfair way to do it.~

Updated: as discussed [here](https://github.com/tskit-dev/msprime-1.0-paper/issues/2#issuecomment-769260290), we're adopting a 4-category author system, with authors listed alphabetically within those categories.

**Comment by petrelharp** [comment]
>  we're not currently including contributions to code that is not part of tskit.

I think you mean "not including code that *is* part of tskit"?

**Comment by jeromekelleher** [comment]
Good spot, thanks. I meant "code that is **now** part of tskit." I've edited the comment above.

**Comment by jeromekelleher** [comment]
Quick question @hugovk: what's the correct way to sort your name in the alphabetical listing above?

**Comment by hugovk** [comment]
I don't mind too much.

The correct way depends on the country. In the Netherlands, it'd be sorted under K, but most other countries sort under V, so V is probably best here. 

Also, when the surname does not follow the first name, you use a big V for Van in the Netherlands. Elsewhere varies. 

The CPython ACKS file uses Dutch sorting, but that'll be because of GvR :) 

https://github.com/python/cpython/blob/master/Misc/ACKS

Of course, if the publication has their own style guide on this, follow that.

See also:
https://academia.stackexchange.com/q/8870
https://en.wikipedia.org/wiki/Van_(Dutch)#Collation_and_capitalisation

Thanks for asking!

**Comment by jeromekelleher** [comment]
Thanks for the explanation @hugovk --- sorting is important! Does the list above look OK to you now?

**Comment by hugovk** [comment]
Looks good, thanks!

**Comment by winni2k** [comment]
> All authors will be listed in alphabetical order of surname, as this seems like the least unfair way to do it.

It occurs to me that reverse alphabetical ordering might be even less unfair?

**Comment by jeromekelleher** [comment]
> It occurs to me that reverse alphabetical ordering might be even less unfair?

Why?

**Comment by winni2k** [comment]
Because it puts first the names that are usually last in alphabetical order. It's an affirmative action argument for last names starting with Z or A, depending on whether you think it's better to be first or last in such a list.

**Comment by shajoezhu** [comment]
My name should definitely not to go first. lol.

**Comment by jeromekelleher** [comment]
> Because it puts first the names that are usually last in alphabetical order. It's an affirmative action argument for last names starting with Z or A, depending on whether you think it's better to be first or last in such a list.

OK, fair enough. It might be less obvious that we're listing the names in alphabetical order then, though, and so people might be less likely set aside the usual precedence rules in biology. 

I don't really mind though, if a majority of authors prefer Z->A instead of A->Z, I'm fine with that.

**Comment by winni2k** [comment]
> It might be less obvious that we're listing the names in alphabetical order then, though, and so people might be less likely set aside the usual precedence rules in biology.

That is true as well.

**Comment by winni2k** [comment]
@jeromekelleher "Winni" is my nom de guerre. For citations that might end up on google scholar I go by "Warren W. Kretzschmar" or "Warren Kretzschmar".

**Comment by jeromekelleher** [comment]
Fixed - thanks Winni.

**Comment by jeromekelleher** [comment]
@saunack - I've added your name above, can you check if I've got it right please?

**Comment by saunack** [comment]
@jeromekelleher My first name is actually Kumar. We've got a different naming convention where I live(in my state specifically), so I am referred to as Saunack by everyone.

**Comment by jeromekelleher** [comment]
Aha, thanks @saunack, fixed!

**Comment by jeromekelleher** [comment]
@nspope, I'd like to add you as an author here for the important bug-fix in https://github.com/tskit-dev/msprime/pull/1130. Can you tell us the preferred form for your name please?

**Comment by nspope** [comment]
@jeromekelleher Thanks, my name is Nathaniel Pope.

**Comment by jeromekelleher** [comment]
@mufernando, @castedo, I just added your names to the list here. Can you verify these are in the right form, please?

**Comment by castedo** [comment]
Nice! Thank you! I try to include my legal first name initialized to provide a useful detail for matching, so:
"Ellerman, E. Castedo, @castedo"

**Comment by mufernando** [comment]
Thanks, Jerome! Could you include my middle name's initial?

Rodrigues, Murillo F., @mufernando

**Comment by jeromekelleher** [comment]
After much reflection, I've changed my mind on the author ordering issue, and decided to adopt the convention that we've been using in the PopSim Consortium (e.g., on [this paper](https://elifesciences.org/articles/54967)) and to split the authors into four groups:

- First authors: those that have contributed a significant feature to msprime **or** substantially contributed in other ways
- Middle authors: those that have contributed code/documentation/etc
- Senior authors: sustained leadership
- Corresponding author: me 

While these are necessarily fuzzy categories, I've come to the conclusion that this is less unfair than the just listing everyone alphabetically. The academic credit system in Biological sciences is what it is, and being able to say "joint first author" on a paper is genuinely valuable to people. There *are* people here who have put in far more work than others, and it's unfair to them if this isn't acknowledged. Also, I think it's fair to say that my ability to attract funding to sustain msprime development in the long term is probably materially affected by whether my name appears at the end of this list or not (sadly).

Does anyone object to this?

I haven't gone through the list with a proposed assignment of the names to bins, yet - if you have an opinion on which category you should be in, please do let me know offline. We are gearing up for the msprime 1.0 software release, so a draft of the paper isn't far away, hopefully.

**Comment by jeromekelleher** [comment]
@cdquinto, can you check if I have your name right above please?

**Comment by cdquinto** [comment]
For publication, I used full name (almost): Consuelo D. Quinto-Cortés.
Thanks :)

**Comment by jeromekelleher** [comment]
After much thought and discussion with the senior authors, we've come up with the following list, which we hope acknowledges everyone's contributions in the fairest possible manner:

# First:

- Baumdicker, Franz, @fbaumdicker, Gene conversion
- Bisschop, Gertjan, @GertjanBisschop, Mutation models implementation & verification
- Goldstein, Daniel, @daniel-goldstein, Simulate in physical coordinates
- Gower, Graham, @grahamgower, RecombinationMap APIs, demography, bugfixes
- Ragsdale, Aaron, @apragsdale, Miscellaneous docs, multiple chromosomes, demography
- Tsambos, Georgia, @gtsambos, Documentation, Census events
- Zhu, Sha, @shajoezhu, Lambda coalescents

# Middle:

- Eldon, Bjarki, @eldonb, Lambda coalescents
- Ellerman, E. Castedo, @castedo, C refactoring, performance improvements
- Galloway, Jared, @jgallowa07, Population size trajectory
- Gladstein, Ariella, @agladstein, Documentation, Docker
- Gorjanc, Gregor, @gregorgorjanc, Writing
- Guo, Bing, @gbinux, Verication for sweeps, documentation
- Jeffery, Ben, @benjeffery, Infrastructure, bug fixes
- Kretzschmar, Warren W., @winni2k, CLI improvements
- Krukov, Ivan, @ivan-krukov, Recombination rate performance
- Lohse, Konrad, @KLohse, Bottlenecks
- Matschiner, Michael, @mmatschiner, Species tree parsing
- Nelson, Dominic, @DomNelson, DTWF
- Pope, Nathaniel, @nspope, C code refactoring, DTWF migration rate clarification
- Quinto-Cortés, Consuelo D., @cdquinto, Documentation
- Rodrigues, Murillo, F. @mufernando, Mutation time
- Saunack, Kumar, @saunack, Refactor verification tests
- Sellinger, Thibaut, @TPPSellinger, Verification for Lambda coalescents
- Thornton, Kevin, @molpopgen, Documentation, nextafter bugfix, community
- Van Kemenade, Hugo, @hugovk, Remove Python 2 support
- Wohns, Anthony W, @awohns, Documentation
- Wong, Yan, @hyanwong, Documentation, RecombinationMap IO

# Senior:

- Gravel, Simon, @sgravel, DTWF
- Kern, Andrew, @andrewkern, Selective sweeps
- Koskela, Jere, @JereKoskela, Full ARG, Likelihoods, Lambda coalescents
- Ralph, Peter, @petrelharp, Lots of things

# Corresponding

Kelleher, Jerome, @jeromekelleher

**Comment by jeromekelleher** [comment]
One more thing authors: can you check your details as described in #122, and either open a PR to update, update in the Overleaf version or email me please. Thanks.

**Comment by ashander** [comment]
Thanks @jeromekelleher this bin strategy looks like a good place to end up. Thanks for the specific note on my contribs --- I'll be on the look out for details about tskit

**Comment by mufernando** [comment]
thanks, @jeromekelleher. I think there is a typo - an extra comma - after my first name. I corrected it below.

Rodrigues, Murillo F. @mufernando, Mutation time
