### ISSUE TITLE
Email address for hugovk

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#200]
@hugovk, I need some email address for you in order to complete the submission forms for Genetics (which is **super tedious**!)

Would you mind emailing me please with an address I can use? jerome.kelleher@bdi.ox.ac.uk

**Comment by hugovk** [comment]
Email sent!

**Comment by jeromekelleher** [comment]
Thanks @hugovk! I don't seem to have gotten the email though - maybe dm-ing via twitter would be simpler? I'm https://twitter.com/jeromekelleher

**Comment by hugovk** [comment]
I'm at Gmail, same username as here ;)

**Comment by jeromekelleher** [comment]
Great, thanks @hugovk!
