### ISSUE TITLE
Make plots and captions more systematic

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#202]
There are a number of inconsistencies in the figure presentation, as pointed out by Reviewer 1:

>  However, I think they could benefit from more cohesive presentations and descriptions. I will provide a number of examples - figure 3 and figure 4 present running times of various aspects of msprime, but present similar data in different ways. In Figure 3, the data points are not presented directly, while they are present on Figure 4. And based on the descriptions sometimes replicates are summed over (Figure 7) or averaged over (Figure 8?) to determine the values on the y-axis. Figure 3 clearly specifies sim_mutations as the input for the benchmark, while for most other figures (e.g. 4) it frequently just says something like "running time for msprime." Sometimes only population-size scaled rates are provided in descriptions (e.g Figure 5 and 7) while in others both scaled and absolute sizes are provided. Sometimes "samples" are described to be diploid (figure 1) or sometime haploid (Figure 3), but other times the ploidy is left implied (e.g Figure 4). Sometimes the population size is referred to "effective population size" (e.g Figure 4) and other times just "population size" (Figure 3). More consistency in these simulations, descriptions, and figures could add clarity to the presentation. I did find the lack of a disk storage benchmark an interesting choice, as this aspect of the software is highlighted in the introduction but is not present in the manuscript. The algorithmic details of the simulations and methods are generally not included in the current manuscript (with some presented in the supplement, and some available in the 2016 paper), and are left for citations. I think this decision serves the manuscript well otherwise it would likely become unwieldy.

>Figure comments
>Figure 2
>I think it could be made more clear that the genotype matrix is not part of the set of tables.
>Figure 4
>It is not clear if these two plots present all the data used for the quadratic fits, or if these data continue outside of the plots.
>Samples are described, but not their ploidy, are they haploids or diploid?
>From the plots here, it is not clear if the quadratic relationship holds for sample sizes << 1000. I suggest this figure should also include a smaller sample size, (eg n=10)
>Figure 5
>I suggest including the absolute Ne and gc rates be included in the legend, in addition to the scaled rate.
>Figure 7
>Why is an order of magnitude lower recombination rate used here than in other examples? This choice seems arbitrary and makes it difficult to relate these benchmarks results to any others in the paper.
>Samples are diploid or haploid?
>I would suggest the absolute Ne and s rates be included in the legend, in addition to the scaled rate.
>Figure 8
>Averaged points are referenced but not shown "Each point...". The plot could be more clear where the data points are and where the lines are interpolating between data points.
>Because of how the simulations were described and plotted, I found it awkward to try to compare the running time of the DTWF and coalescent models, even if this was not the purpose of the current figure.
>The figure says "to ensure we are measuring" I would suggest changing the text to "with a goal of measuring".

(Some of these points might be more appropriate in a separate issue, but we can create those as we go. I think the majority of these points can be addressed in a single "tidy up" pass through the figures and captions.)

**Comment by castedo** [comment]
OK, I've got an improved figure 2 cooked up in PR #208. Let me know if you see anything tweaking.

Makefile and inkscape worked great!
