### ISSUE TITLE
Absolute values in GC figure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#213]
Reviewer 1:

> Figure 5 I suggest including the absolute Ne and gc rates be included in the legend, in addition to the scaled rate.

I responded:

> We avoided included the absolute values here in order to make the comparison between the simulators as simple as possible (since SimBac and FastSimBac required scaled inputs). Since the values we use aren't precisely the estimates for E.~coli (we rounded some values for simplicity), it would probably be misleading to include some Ne and gc rates that are consistent with the scaled value we used, but not equal to the actual E.~coli estimates, and we would therefore prefer not to include them.

Is this OK @fbaumdicker? Or should we just redo the figure with the actual estimates?

**Comment by fbaumdicker** [comment]
I think this should be perfectly fine. But if the reviewer insists on adding absolute values, then it would be easy to change the parameters and rerun. I doubt that there would be a visible difference though.

**Comment by jeromekelleher** [comment]
I've started running the real parameters - if that completes in a reasonable amount of time we'll use it, but we can use the argument above otherwise.
