### ISSUE TITLE
a few very small comments

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime-1.0-paper#233]
it looks great,  only a few very small comments:

0)  maybe state in the introduction that  the coalescent  also works so well because the mathematical construction of it separates the  mutation process from the  ancestral process, and this is true for coalescent model derivations in general;  there is an exception in a  paper by Simon Tavare (https://pubmed.ncbi.nlm.nih.gov/6505980/)
https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.595.1777&rep=rep1&type=pdf
see Section 4, where he  discusses  the derivation of an ancestral process with mutation, but I don't know of an  implementation of his construction in  a computer code
@article{tavare1984line,
  title={Line-of-descent and genealogical processes, and their applications in population genetics models},
  author={Tavar{\'e}, Simon},
  journal={Theoretical population biology},
  volume={26},
  number={2},
  pages={119--164},
  year={1984},
  publisher={Elsevier}
}

1)  my manuscript with Alison and Jono 'Multiple merger coalescents, bounded juvenile numbers, and  large sample sizes'  
is now called  'Beta-coalescents when sample size is large'; unfortunately still in  progress,  I've tried to push it along but with the current situation 

 2) lines 312-313: do we need to explain the difference between  'branch-by-branch' and 'edge-by-edge'  ways of adding mutations ?
I suppose it  centers on the difference between a 'branch' and an 'edge' ?

3) should we provide a short  overview/summary of how the paper is structured, maybe at the end of the introduction ?

4) line 435: would be nice to add
@article{vendrami2021sweepstake,
  title={Sweepstake reproductive success and collective dispersal produce chaotic genetic patchiness in a broadcast spawner},
  author={Vendrami, David LJ and Peck, Lloyd S and Clark, Melody S and Eldon, Bjarki and Meredith, Michael and Hoffman, Joseph I},
  journal={Science advances},
  volume={7},
  number={37},
  pages={eabj4713},
  year={2021},
  publisher={American Association for the Advancement of Science}
}
to the list of references on highly fecund organisms, since this paper provides the most convincing empirical evidence yet of sweepstakes reproduction, and by implication the relevance of multiple merger coalescents

line 557 :  it seems to matter how one  relates forward and backward simulations; I have experimented  with this a bit, and  not all ways of doing this  are  appropriate; there is some mathematical work on this  e.g. under the concept of 'fixation line';  I don't think we need to elaborate on this here, but  I think this is more subtle than it may seem at first
@article{henard2015fixation,
  title={The fixation line in the $$\{$$\backslash$Lambda$\}$ $-coalescent},
  author={H{\'e}nard, Olivier},
  journal={The Annals of Applied Probability},
  volume={25},
  number={5},
  pages={3007--3032},
  year={2015},
  publisher={Institute of Mathematical Statistics}
}

line 571: maybe replace 'Development model' with  'Community-based approach'  or something similar ?

lines 611-614: feels like repeat from the section 'Development model' ?

line 627:  can something be 'high quality' ?  I could be wrong, but  I thought  either something is 'quality'  whatever, or it is not ?

line 1179: what is 'total' ?  are we summing the rates, or  choosing the larger of \alpha  and \beta ?

line 1295:  slightly more precise to say: 'in which no more than one group of a random number of ancestral lineages may merge'

**Comment by jeromekelleher** [comment]
Thanks for this @eldonb. I'm not sure whether we should be making changes that weren't requested by the reviewers.

Perhaps you could open a PR (or PRs) with the changes that you're sure should be made, and maybe we could discuss the others then?

**Comment by eldonb** [comment]
I tried to open a PR (pull request ?)  but  somehow it did not work ; 

 1. and 4. from above  would be good to see, they only regard the references;  I'm happy to discuss the others,  they were only meant as possible  additional clarifications

**Comment by jeromekelleher** [comment]
OK, thanks @eldonb. I'll incorporate these next week and ping you for review.

**Comment by jeromekelleher** [comment]
I've changed the citations in #235, and pinged you over there for a review @eldonb.

With the rest, it's not clear to me what version of the paper the line numbers are referring to, so it's not obvious how to address then. It should be straightforward enough to make small changes - if you use the Github interface to look at [paper.tex](https://github.com/tskit-dev/msprime-1.0-paper/blob/main/paper.tex) you can suggest changes by clicking on the pencil icon. This should be fine for making small updates.

**Comment by eldonb** [comment]
thanks @jeromekelleher 

the citations changes are good, and I  added  some  very small suggestions for  changes of the text (hope you can see them)

the line numbers refer to the Github version of paper.tex

line  217: an addition about  separating the mutation process from the  ancestral process

line 873: suggested replacement for 'human-like'

line 1452: suggested 'Community-based approach'  as replacement for 'Development model'

just small suggestions, either way is fine with me

**Comment by jeromekelleher** [comment]
These have been addressed now I think, thanks @eldonb!
