### ISSUE TITLE
Finalise grant details

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#242]
As you may have heard, the paper has been accepted for publication :tada:

One thing I brushed over in the initial submission was the process for adding grant details online. I spent about an hour struggling with it and gave up in despair, after being reassured we could fix it later. Later is now, unfortunately :wink:

So, if you have grant information that you want/need to acknowledge, can you please send me *all* of the details that you can get (including website links etc etc) so that I can appease the website? An email would be ideal. 

@agladstein
@andrewkern
@apragsdale
@awohns
@benjeffery
@castedo
@cdquinto
@daniel-goldstein
@DomNelson
@eldonb
@fbaumdicker
@gbinux
@GertjanBisschop
@grahamgower
@gregorgorjanc
@gtsambos
@hugovk
@hyanwong
@ivan-krukov
@JereKoskela
@jeromekelleher
@jgallowa07
@KLohse
@mmatschiner
@molpopgen
@mufernando
@nspope
@petrelharp
@saunack
@sgravel
@shajoezhu
@TPPSellinger
@winni2k

**Comment by molpopgen** [comment]
None

**Comment by KLohse** [comment]
GB and KL are supported by an ERC starting grant (ModelGenomLand 757648) to KL

**Comment by TPPSellinger** [comment]
None as well.

**Comment by cdquinto** [comment]
None

**Comment by daniel-goldstein** [comment]
None

**Comment by jeromekelleher** [comment]
Genetics just got back to me and said, don't worry about the web form, just make sure the details are correct in the manuscript. So, if you have grants you need to ack, please take a final look at the [Funding](https://github.com/tskit-dev/msprime-1.0-paper/blob/807c42f48b3db77616b97efd56f880e4c3130392/paper.tex#L1623) section and make sure that you are happy with what's there.

Apologies for all the noise, it's all very messy and opaque to me.

**Comment by agladstein** [comment]
NIH award R00HG008696

**Comment by eldonb** [comment]
my relevant grant info is already recorded -  
thanks @jeromekelleher 

will the new  accepted version appear on    biorxiv ?

**Comment by jeromekelleher** [comment]
Thanks @eldonb 

> will the new accepted version appear on biorxiv ?

I wasn't planning on it - I'm not sure what Genetics' policy on this is? Happy to post the pre-genetics-ified version if others would like to see it and it's OK with Genetics.

Going to close this issue anyway, as I've posted the final versions to the production team

**Comment by petrelharp** [comment]
> I wasn't planning on it - I'm not sure what Genetics' policy on this is? Happy to post the pre-genetics-ified version if others would like to see it and it's OK with Genetics.

I think we should do it - I've done this for all my papers, at least.

**Comment by andrewkern** [comment]
+1

I think we should definitely post the accepted version to biorxiv

**Comment by jeromekelleher** [comment]
OK, will do unless I see something directly saying I shouldn't while going through the copyright rigamarole

**Comment by apragsdale** [comment]
Agree we should update. But I have found biorxiv to be very strict about not allowing revisions once a paper is accepted.

The decision letter reads, "We are delighted to inform you that your manuscript entitled "Efficient ancestry and mutation simulation with msprime 1.0" is _acceptable_ for publication in GENETICS." (emphasis mine). So we could say it is not yet officially accepted, but only "acceptable".

**Comment by jeromekelleher** [comment]
The paper will be published OA soon anyway, so I'm not sure it makes much difference, but I'll see if I can post the accepted version today.
