### ISSUE TITLE
Change figures to suit two-column format

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#243]
The current figures are mostly optimised to fill the width of a single column page. I converted the manuscript to genetics format (attached here for convenience) without worrying too much about the details. Do people have opinions about how we should proceed?

We could:
1. Leaves things as they are and see what the production team suggest
2. Fix them up so that we think they look good first (and then potentially have the production team change it all again)

I'm leaning towards (2).

To me, Figures 3, 4, 6, and 7 should remain two-column page spanning figures. 

I'm not sure what to do with the rest.

Any thoughts?

[paper.pdf](https://github.com/tskit-dev/msprime-1.0-paper/files/7654061/paper.pdf)

**Comment by gregorgorjanc** [comment]
I agree re 3, 4, 6, and 7!

What then for 1, 2, and 5? Stack panels on top of each other? Arguably this could be done for all figs:(

**Comment by jeromekelleher** [comment]
Fig 1. will look fine stacked vertically I think.

Fig 2. Needs to stay left-to-right, but we could make it small enough to fit in one column, possibly. The fonts will get awful small then though (@castedo, any thoughts here?)

Fig 5. I don't know what to do here. I don't think it can be shrunk to one column. It could be OK stacked vertically, but I'd need some help from the tikz experts - any thoughts @grahamgower, @gtsambos?

**Comment by grahamgower** [comment]
> Fig 5. I don't know what to do here. I don't think it can be shrunk to one column. It could be OK stacked vertically, but I'd need some help from the tikz experts - any thoughts @grahamgower, @gtsambos? (Because it's tikz we definitely want to get it into more-or-less the way we want it before passing it on to production, I'd be surprised if they'll be able to edit it well)

I can't seem to build the manuscript anymore:
```
! LaTeX Error: File `styles/inv.sty' not found.`
```

But it looks like Fig 5 subfigures are each separate tikzpictures, so they should be vertically stackable without any tikz-fu by using regular latex. Maybe just change `\begin{subfigure}[t]{0.33\textwidth}` to whatever width is needed, and append `\\` after `\end{subfigure}`?

**Comment by molpopgen** [comment]
I'm a bit confused.  Genetics uses 2 columns for the text, and only for figures if needed.  There should be no reason to shrink unless page charges are a concern. In the end, what determines the final page charges has more to do with color in the figures than the total number of pages.

**Comment by castedo** [comment]
> Fig 2. Needs to stay left-to-right, but we could make it small enough to fit in one column, possibly. The fonts will get awful small then though (@castedo, any thoughts here?)

My thoughts are that HTML displayed on computer screens is superior to PDF printed on paper. :laughing:

Eye balling the new PDF, I predict a straight up shink-to-one-column without adjusting font size will be too unreadable, and there's too much text that would need to be increased in font size. I can think of a few ways to make the whole figure long and thin (top-to-bottom). But the placement in the text of a long and thin Fig 2 seems questionable.

On Fig 2, seems best to see what the production team suggests.

As a side note, why are they trying to do two columns with a smaller font in the 21st century? Is trying to save paper during physical printing an actual concern? How many sane people are printing these in 2022? This seems so antiquated, like playing historical reenactment. :open_mouth:

**Comment by molpopgen** [comment]
> > Fig 2. Needs to stay left-to-right, but we could make it small enough to fit in one column, possibly. The fonts will get awful small then though (@castedo, any thoughts here?)
> 
> 
> 
> As a side note, why are they trying to do two columns with a smaller font in the 21st century? Is trying to save paper during physical printing an actual concern? How many sane people are printing these in 2022? This seems so antiquated, like playing historical reenactment. :open_mouth: 
> 

Two things

1. Most papers published in genetics do not have the figures in one column. This is the reason why I made my comment above. I think this is energy misspent. Take a look at articles in the current issue. Most figures in most papers span both columns

2. The reason to worry about how it looks at PDF is that there's a sizable chunk of the world with no online access for scientists. There are still print copies of the journal, and those of us that are society members often donate our subscriptions, which means we don't take the print copy. They are mailed to libraries in countries where online access is a problem.

**Comment by sgravel** [comment]
Even without internet restrictions, I much prefer to read from the pdf layout.  In any case, I don't think we will change the genetics policy here. 

I think it is good to make a reasonable effort to make the figures fit in the one column format if natural, as it minimizes breaks in the layout. This being said, if you feel like a figure is best presented horizontally, I would not sweat it and keep it horizontal on two columns. Shrinking and making tiny fonts is never recommended. If it's too much work to shrink while keeping fonts large, I would keep the larger figure. 

Figs 3, 4, 6, 7 could easily be scaled to fit horizontally in a single column with appropriately scaled fonts. On a pdf, having figures larger than they need to be does detract from readability. 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/6934404/144726880-ee7ebb56-9ac5-46c8-b6ec-ffe96655c5f3.png">

**Comment by castedo** [comment]
> 2. The reason to worry about how it looks at PDF is that there's a sizable chunk of the world with no online access for scientists.

On a more serious note, even though it's 2021, I agree PDF is the best archival format (and not HTML). Now on the medium being literally paper ... I bet there intersection between scientists who would use msprime and scientists who need to get journals in printed paper form because they have no internet access is zero.

> Even without internet restrictions, I much prefer to read from the pdf layout.

@sgravel You prefer to read on printed paper or just in pdf layout on a electronic device?

> In any case, I don't think we will change the genetics policy here.

I'm going to hold my breath! That will convince someone to change the policy. :face_with_spiral_eyes:

**Comment by sgravel** [comment]
> @sgravel You prefer to read on printed paper or just in pdf layout on a electronic device?

I enjoy reading on paper more, if I am being honest, but rarely do so because of convenience and environment. PDF has the best balance for me of tolerable layout and convenience.

**Comment by jeromekelleher** [comment]
> I can't seem to build the manuscript anymore:

Oops, sorry @grahamgower - fixed now.

**Comment by jeromekelleher** [comment]
Thanks very much for the input everyone, this is hugely helpful. I've tried a few things out and I think @sgravel is right, in the that the main performance plots are perfectly legible when pushed into a single column. I updated the paper in #248 to do this. I've attached the current state of the paper here for convenience:

[paper.pdf](https://github.com/tskit-dev/msprime-1.0-paper/files/7655991/paper.pdf)

I left figure 8 as spanning two columns, as it's quite dense already and would be a lot of work to shrink down.

Answering some of the points above:

- I think it's good to give the typesetters something close to what you'd ultimately like to see, otherwise it's a frustrating experience for all concerned, and it'd be a shame to not be happy with the final product after such a long journey. 
- PDFs are a bit of an anachronism, but that's the way it is. We should maximise readability in the PDF, as it's rendered (and will remain rendered)
- Personally, if I'm really reading a paper I'll go with the PDF, the web HTML versions are still all pretty crap to be honest.
- Page charges aren't really a concern here, it's about making it as easy as possible for readers and (let's be honest) making the final product look good.

WRT the remaining figures:
- Figure 1. is problematic. @hyanwong, is there any chance you could have a look at this and see what you think is best please?
- Figure 2. I'm happy to leave as-is and see what the typesetters suggest
- Figure 5. I tried fiddling with this, but didn't arrive at anything acceptable looking. @grahamgower, do you think you could have a look please?

**Comment by hyanwong** [comment]
> Figure 1. is problematic. @hyanwong, is there any chance you could have a look at this and see what you think is best please?

It would be easy to put the two tree sequences one above the other. Shall I do this?

**Comment by jeromekelleher** [comment]
Yes please!

**Comment by hyanwong** [comment]
Do we want a y (timescale) axis on these plots?

**Comment by hyanwong** [comment]
How's this (roughly - ignore the screenshot shading). I changed the mutation random seed to get nicer label layouts:

<img width="347" alt="Screenshot 2021-12-05 at 16 06 13" src="https://user-images.githubusercontent.com/4699014/144754083-540e60a1-aeb8-4b06-b59c-2ddfdfde15b7.png">

Or here with a Y axis: too busy?

<img width="367" alt="Screenshot 2021-12-05 at 16 16 52" src="https://user-images.githubusercontent.com/4699014/144754453-a45b97a6-8a39-4ae5-9477-666b98a02278.png">

**Comment by jeromekelleher** [comment]
Either looks good to me - depends on how it looks in the context of the document really. Your call.

**Comment by jeromekelleher** [comment]
Thanks to @grahamgower and @hyanwong we now have all the figures updated (except fig 2): hooray! I've attached the current build, which I think is looking really good. I expect there'll be a few tweaks, but I think it's good enough to pass on now.

I'll get the uploads done tomorrow. Thanks all!

**Comment by jeromekelleher** [comment]
Just submitted the "final" version :tada: I'll update if there's anything significant to report from the production team. Hopefully they'll just take the Latex file as-is :crossed_fingers:

**Comment by hyanwong** [comment]
I just noticed: the right hand "Megabases" label in fig 6 has had the closing bracket cut off.
