### ISSUE TITLE
citation "numbering" (a, b, etc.) doesn't match citation order

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime-1.0-paper#253]
E.g. see the intro where Kingman 1982`b` comes before `a`. Likewise Hudson 1983`b`. I guess this is something to do with the ordering in the bib file or the alphabetical ordering of `kingman1982coalescent` versus `kingman1982genealogy`?
![cite](https://user-images.githubusercontent.com/8665077/144815303-6958e551-267e-45a5-bdce-7b69b6db1fc9.png)

**Comment by jeromekelleher** [comment]
I don't know off the top of my head - try fiddling with the order in the bib file maybe?

**Comment by grahamgower** [comment]
Happy to ignore it. The copy editor will take care of this if they care, right?

**Comment by jeromekelleher** [comment]
Likewise
