### ISSUE TITLE
Daniel Goldstein's affiliations wrong

### ISSUE THREAD

**Issue by castedo** [tskit-dev/msprime-1.0-paper#263]
Sorry to report that the affiliations of @daniel-goldstein are wrong. Currently they are listed as:
* Northeastern University
* No affiliation

I believe what is correct is
* Northeastern University
* Broad Institute of MIT and Harvard

This is currently appearing in the PDF associated with
  https://doi.org/10.1093/genetics/iyab229
and also the PubMed metadata:
  https://pubmed.ncbi.nlm.nih.gov/34897427/

I am the proximate cause of this error with my PR #224. That said, a "but-for cause" ([sine qua non](https://en.wikipedia.org/wiki/Sine_qua_non)) is Daniel did not do a full renumbering cascade when he added his second affiliation in PR #194. I didn't notice that the numbers were already out of order at the very beginning of the list when I did my PR.

Since the git repository is not longer the [source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth) I'm not sure it's worth fixing this in git. But @jeromekelleher or @petrelharp just let me know if you want me to make another PR for the proximate cause PR I did. I'm happy to clean up the error I made.

As a side note, I think a really useful tool for humanity, which I can code up if one doesn't exist, is the automated generation of latex lines with author and affiliation lists given a yaml file of authors and affiliations. Ideally this kind of number ordering should be done by computer and not humans with limited cognitive capacity like me. :sweat_smile:

**Comment by petrelharp** [comment]
Whoops! Thanks for noticing. Yes, could you do a PR? It's easy and we can at least update the preprint with this.

**Comment by castedo** [comment]
OK, will do this week. Feel free to assign this github issue to me.
