### ISSUE TITLE
Discussion of coalescent scaling

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#28]
It would be useful to give people an idea of when msprime is fast and when it isn't, and why.

Some version of this plot from @petrelharp and a discussion would be great.

![screenshot_from_2021-06-17_10-06-44](https://user-images.githubusercontent.com/2664569/122533524-93f50400-d019-11eb-866e-a294668e5d13.png)

**Comment by petrelharp** [comment]
Want me to put the code to make this figure in this repo?

**Comment by petrelharp** [comment]
I can also draft this discussion at some point.

**Comment by jeromekelleher** [comment]
Both would be great, thanks!

**Comment by jeromekelleher** [comment]
Ideally including the CSV of the data points.

**Comment by jeromekelleher** [comment]
@petrelharp, #32 added a placeholder for this discussion in the "Recombination" section and a figure. Do you think you'll get to this some time soon?

**Comment by petrelharp** [comment]
Um, not this week? Depends how urgent it is? I will try for next week.

**Comment by jeromekelleher** [comment]
Next week would be great - even a rough brain dump with the script/plot/data would be excellent, I can polish.

**Comment by sgravel** [comment]
There is a relevant discussion in section 5.5.3 of Genes, Genealogies, Variation, and Evolution by Hein, Schierup, and Wiuf that discusses expected scaling of Hudson's coalescent. In particular, it shows that the scaling of the number of operations in Hudson's is bounded by a quadratic (Equation 5.10). The bound on the number of "trapped" recombinations (i.e., that occur between ancestral segments) is $E(R)\leq \rho (\rho+1) \sum_{I=1}^{n} \frac{1}{i} $ For simulations of long regions, this will be the dominant term, and the expected number of operations should scale as $2 E(R)$. 

I'm happy to summarize this in the paper if there. is interest. Also wonder if we could use this in the figure and/or as a strategy to estimate runtime. I.e., if we can estimate a cost-per-operation, this would provide an upper-bound formula for the expected runtime.

**Comment by jeromekelleher** [comment]
It would be great if you could summarise this in the paper @sgravel - I think it's fair to say it's an under-appreciated fact!

**Comment by sgravel** [comment]
I added a very short blurb on this. Let me know if you want something more or less detailed. 

The intro mentions 
`While the single-locus coalescent for $n$ samples can be simulated in $O(n)$
time~\citep{hudson1990gene}, the coalescent with recombination is
far more challenging.` 
I don't really disagree, but this may be confusing. The scaling of the the coalescent with recombination with $n$ is also technically $O(n)$, if I am not wrong. The costly term probably has the form $\rho^2 log(n)^2,$ if I take the bound in Hein Schierup and Wiuf as tight. Maybe it would be more clear to say that  `the complexity of the coalescent with recombination increases rapidly with simulated length`?

**Comment by jeromekelleher** [comment]
Hmm, but if rho^2 >> n, then doesn't the complexity become O(rho^2)?

I agree we should make this less technical, though - your phrasing looks good to me.

**Comment by sgravel** [comment]
Right, I think my confusion was just because I was trying to tie the "more challenging" directly to the "O(n)", and then I started asking myself questions about order of limits and assumptions about size of parameters that I don't think were that relevant to this discussion.

**Comment by petrelharp** [comment]
I think was closed by #88, although we haven't put in anything about the scaling of DTWF, which SImon said over there was O(N^2 L) instead of O((NL^2)). I'll close this and open an issue for that.
