### ISSUE TITLE
Comparison with ARGON

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#29]
@gtsambos has been doing some work comparing msprime with ARGON, so it'd be nice to include a plot somewhere illustrating.

@gtsambos, can you paste in here the figure you have currently please so we can discuss?

**Comment by gtsambos** [comment]
Sure! Here are some figures showing how runtimes in msprime and ARGON compare to each other.

For different sample sizes:
![Screen Shot 2021-06-03 at 6 45 26 pm](https://user-images.githubusercontent.com/17755074/122691567-d0bc3780-d273-11eb-99a3-39e2dfc0fe57.png)

For different simulated contig lengths:
![Screen Shot 2021-06-03 at 6 45 10 pm](https://user-images.githubusercontent.com/17755074/122691578-dfa2ea00-d273-11eb-88e2-65ec9bf7d51b.png)

Each datapoint uses 5 replicate simulations from each program. In both cases, the simulations are DTWF,  a single population of size 1000 (1000 haploids in ARGON, 500 diploids in msprime). Recombination rate is 1.0E-8 per bp per gen, mutation rate is 1.65E-8 per bp per gen, the ARGON defaults.

**Comment by gtsambos** [comment]
I also did some plots illustrating that msprime and ARGON are simulating comparable things. These plots were made by running 5 simulations under each program, [converting the ARGON output](https://github.com/tskit-dev/tsconvert/pull/18) into tree sequence format, and using standard tskit functions.

Distributions of (ancestral) node times:

![Screen Shot 2021-06-17 at 1 56 50 pm](https://user-images.githubusercontent.com/17755074/122691775-f990fc80-d274-11eb-85e8-40ffd130edb2.png)

Distributions of tree spans:

![Screen Shot 2021-06-17 at 1 57 02 pm](https://user-images.githubusercontent.com/17755074/122691798-07468200-d275-11eb-9ec1-f9dc8c7fe3ff.png)

**Comment by jeromekelleher** [comment]
@gtsambos - any update on this? It would be nice to get a comparison of running msprime and ARGON minus the IBD calculations in pretty soon. So, we'd like to run msprime in DTWF mode and ARGON with as little as possible turned on. The ideal thing would be to run ARGON with all output turned off, so that we're just measuring how long it takes to run the simulation (but this probably isn't possible).

If possible, it would be nice to run msprime in hybrid mode also, with (say) 100 generations of DTWF followed by Hudson. So, we'd have three lines "msprime DTWF", "msprime Hybrid" and "ARGON".

**Comment by gtsambos** [comment]
@jeromekelleher - did you see my posts above from a few weeks ago? I was
waiting to hear back from you before I did any more work on these plots,
because it sounded like you wanted to discuss them further. Let's talk
about it in our call soon.

**Comment by jeromekelleher** [comment]
Closed in #109
