### ISSUE TITLE
Citation data from SCOPUS

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#30]
I looked this up out of curiosity - it's probably of no interest for the paper, but I thought I'd record it here in case it was.

This is from data collected 2021-06-27

![plot](https://user-images.githubusercontent.com/2664569/123547550-26ec1780-d759-11eb-87a3-eabf669a997a.png)

Data:
```
year,msprime,ms,scrm,macs,cosi2
2014,0,119,0,26,0
2015,0,93,2,24,3
2016,1,131,8,21,6
2017,7,82,6,20,1
2018,24,96,7,18,1
2019,39,78,14,19,2
2020,49,77,7,22,1
2021,27,27,6,7,1
```
Code:
```python
import pandas as pd
import seaborn as sns

df = pd.read_csv("msprime.csv")
df = df.set_index("year")

ax = sns.lineplot(data=df, markers=True, dashes=False)
ax.set_ylabel("Citations per year (SCOPUS)")
fig = ax.get_figure()
fig.savefig("plot.png")
```

**Comment by molpopgen** [comment]
Fastsimcoal?  I think thats semi-popular.

**Comment by jeromekelleher** [comment]
Updated. This is just the original fastsimcoal paper; I didn't do fastsimcoal2 because that's also an inference method. (Adding the data involves hovering over points in a plot and putting in the numbers manually into the file, so my curiousity is running out quickly! The CSVs that SCOPUS exports are baffling, this seemed quicker.)

![plot](https://user-images.githubusercontent.com/2664569/123549580-a382f400-d761-11eb-873d-2f57cf90bb1d.png)

```
year,msprime,ms,scrm,macs,cosi2,fastsimcoal
2014,0,119,0,26,0,27
2015,0,93,2,24,3,20
2016,1,131,8,21,6,20
2017,7,82,6,20,1,31
2018,24,96,7,18,1,29
2019,39,78,14,19,2,32
2020,49,77,7,22,1,30
2021,27,27,6,7,1,23
```

**Comment by hyanwong** [comment]
Nice! You could probably double the 2021 figures on the assumption that they cover almost exactly half a year.

I wonder if this plot could even go in a covering letter for the paper? It justifies why msprime needs to be described in a "significant" paper.

**Comment by petrelharp** [comment]
> I wonder if this plot could even go in a covering letter for the paper? It justifies why msprime needs to be described in a "significant" paper.

I don't think we'll have to justify that...
