### ISSUE TITLE
Performance figure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#4]
A key argument in favour of msprime is that it's fast. It's faster than lots of other simulators that only have a subset of its features. We want a figure demonstrating this.

@daniel-goldstein and I just sketched out this:

![IMG_20200218_132955](https://user-images.githubusercontent.com/2664569/74741379-95ab8d80-5254-11ea-8239-880af69bf311.jpg)

The idea is that we compare msprime against other specialised simulators on a variety of applications, and show that it's faster (hopefully).

At the moment, we're looking at 4 panels. We have time on the y axis, and sample size on the x. Fix other parameters at human-ish, and tweak them for each panel so that we can actually run the simulations.

- Standard coalescent: ms, msms, msprime
- SMC approximations: MaCS, scrm, msprime_smc, msprime hudson
- DTWF: Argon, msprime_dtwf
- Sweeps: msms, discoal, msprime sweep

I'm least clear about the sweeps example: @andrewkern, what do you think we should do here? Any other simulators to consider?

Any other simulators we should consider?

**Comment by DomNelson** [comment]
Don't know if you're planning to show anything for longer regions, but (for example) msprime_dtwf also does well for multi-chromosome sims. More generally showing scaling with length could be interesting for some people too, not sure if this particular figure is mainly meant to highlight scaling with sample size.

**Comment by jeromekelleher** [comment]
Good idea @DomNelson, but I think we've already shown this in your paper and I don't think that any other simulator can do that sort of multi-chromosome sim. The point of this figure is to show that msprime can do the same stuff as all these other simulators, but *way* faster. So, we're only interested in doing something here if it can be compared with some other simulator.

**Comment by jeromekelleher** [comment]
@fbaumdicker, should we compare with SimBac here? This seems like a good thing to get in.

I guess if we want to keep a 4 panel figure we could lose the SMC comparison.

**Comment by fbaumdicker** [comment]
I would love to see the comparison with SimBac and ms + gene conversion. Not sure whether any of the other 4 panels can be omitted. It might also be possible to integrate the results into the top left panel.

**Comment by daniel-goldstein** [comment]
@andrewkern I'm starting to put together performance benchmarks for against msms and discoal for sweeps. Do you have a recommendation for appropriate simulation parameters?

**Comment by fbaumdicker** [comment]
Are we also planning to compare to forward simulators? If so we could compare the performance of the new gene conversion feature with
- ms (coalsecent based)
- SimBac (coalescent based) https://github.com/tbrown91/SimBac
- CoreSimul (Forward) https://github.com/lbobay/CoreSimul
- BacterialSlimulations (Forward within SLIM) (according to the preprint this one is faster than ms) https://github.com/jeanrjc/BacterialSlimulations

The last two are recent preprints but look relevant.

Is this something you would support to add @jeromekelleher ?

**Comment by jeromekelleher** [comment]
I'd definitely support adding this @fbaumdicker! However, I'm afraid you/someone else would have to do the work of comparing the simulators - there's no way I'd be able to get the time to do this.

**Comment by fbaumdicker** [comment]
I plan to do this anyway at some point. The question is rather whether it is worth it to spend the time now to add this already to the msprime 1.0 paper or whether we should wait for a future project, regarding variable gc rates and microbial evolution in general?

**Comment by jeromekelleher** [comment]
Well, it's up to you I guess. I assume that for microbial evolution we'd need more sophisticated forms of GC, so there's still work to be done there post 1.0. It would be a nice demonstration for this paper though, and I guess could basically be reused (with some additions) for a later project. It's entirely up to you.

It would be a really nice way to emphasize the point that people are wasting time writing a million and one different simulators...

**Comment by jeromekelleher** [comment]
Created #26 to discuss comparing with bacterial simulators. It may be possible to combine all the performance comparisons into one figure, but lets assume that they are separate for now.

**Comment by jeromekelleher** [comment]
Making one performance figure seems too difficult now, going to close this in favour of separate figures for diffent types of simulations.
