### ISSUE TITLE
"Results" section - should we include example code / benchmarks?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime-1.0-paper#47]
I mentioned this at the end of the online meeting, but I bring it up again after having read the commented-out section in the paper layout that says, of the "Results" section:

> For software, the authors are expected to present a
> few examples that demonstrate the use of the software and benchmarks. 

Does this mean that benchmarks etc (which could, or could not, be taken as meaning some of the plots, such as 1A) should go in this "Results & discussion" section? Or should we simply have a few examples showcasing the paragraphs in the methods - which we could do with "boxes with scripts supported by a narrative" as they recommend.

Or is all this too dependent on the G3 format, which is, I presume, where this structure comes from?

**Comment by jeromekelleher** [comment]
I think we should stick with the established sectioning, and not worry to much about what "super section" they fit in. Splitting the discussion of each of the features into "methods" and "results" would be silly. I think we'll just have a "Results" section that contains all the content, and a separate "Discussion" section.

The structure is currently based on the layout for G3,  but we'll probably submit to Genetics in the first instance (who are flexible, I'm told).

**Comment by jeromekelleher** [comment]
I don't think we should include example code - it's very hard to do well in the context of a typeset document, and it would probably double the length of the manuscript. Anyway, that's what the online documentation is for. This is a high-level discussion of the various features, setting them against the existing literature.

**Comment by hyanwong** [comment]
Right - it's all immaterial if it's aimed at Genetic in the first instance anyway.
