### ISSUE TITLE
Add TOC to pdf?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/msprime-1.0-paper#48]
When editing and looking at the overall structure, I think it might be really handy to have a table of contents in the thumbnail bar (often shown at the left of the pdf viewer).

According to https://tex.stackexchange.com/questions/42343/how-to-add-a-navigation-window-to-a-latex-generated-pdf-document we could do this by adding something like this to the preamble:

```
\usepackage[]{hyperref}
\hypersetup{
    pdftitle={Your title here},
    pdfauthor={Your name here},
    pdfsubject={Your subject here},
    pdfkeywords={keyword1, keyword2},
    bookmarksnumbered=true,     
    bookmarksopen=true,         
    bookmarksopenlevel=1,       
    colorlinks=true,            
    pdfstartview=Fit,           
    pdfpagemode=UseOutlines,    % this is the option you were lookin for
    pdfpagelayout=TwoPageRight
}
```

Is that worth doing, or would that mess too much with the established document layout format that has been given to us? Or could we try it out and remove it if necessary before submission? I'm happy to try it out if given the go-ahead.

**Comment by jeromekelleher** [comment]
If you like - so long as it's easy to turn off again when we're formatting I don't mind.
