### ISSUE TITLE
Feature section: selection 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#8]
We need a feature section for the selective sweeps feature. See #7 for an overview of feature section structures.

@andrewkern, you seem like the obvious person for this?

**Comment by jeromekelleher** [comment]
@andrewkern, this section could use some love. Basically we need something that follows the pattern set in the "Multiple merger coalescents" section for selection. So:

- Background - how does selection work in the coalescent? What are the limitations? General citations.
- Software: what's the software available to simulate the coalescent with selection?
- What did we do?

We'd also like to include a performance figure, comparing with discoal (I guess?). Where are we with that?

Do you think you can get to writing this up sometime soon?

**Comment by jeromekelleher** [comment]
@andrewkern I had a go at making a performance figure here where we do the standard thing of having two panels, varying the sample size and sequence length for some human-like data, based on some example from msprime verification.py. However, hit up against a wall with all the parameter scaling going on, and I started wondering if there's any point. We don't expect discoal to be any faster than msprime when doing the standard coalescent, which is presumably what it spends most of its time doing for most things we simulate. So, perhaps we could just sum this up in a sentence or two rather than going to the trouble of writing code to run evaluations, etc?

Anyone else want to weigh in here?

**Comment by andrewkern** [comment]
Hey Jerome-- I've got time today to work on this. We definitely don't expect discoal to run faster than msprime, but having the fig to prove it would be sweet. Mind if I cook this up?

**Comment by jeromekelleher** [comment]
Go nuts!

**Comment by jeromekelleher** [comment]
Just write a standalone script to generate a CSV with the timing data - don't bother trying to follow any of the existing conventions, I'm currently refactoring stuff anyway, so I'll make it fit in with the other stuff later.

**Comment by jeromekelleher** [comment]
Closing - we have a good draft of the various components.
