### ISSUE TITLE
big-picture comments

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime-1.0-paper#82]
I've done a general read-through of the paper, and am recording big-picture comments here (for lack fo a better place?).

Generally: it looks great!  I'd say that right now it is a general overview of the new features, with demonstrations that these new features are indeed fast. There isn't much detail on how things actually work, except in the Appendix. I think this is probably good - how much detail we want depends on the audience, and adding more detail would make it too long.

1. In the "tree sequence" section, it doesn't yet explain how mutations are put in there.
2. However, the next section does, so maybe that section should be titled "mutations" not "simulating mutations"
3. We've got nothing showing the Demography features. We might have a table of Demography ingredients? Or a diagram of a demography with a few events, with the code to produce it alongside? Right now it feels a bit abstract, and arriving at "instantaneous bottlenecks" feels like then there will be sections for many more demographic ingredients (but there is not). Alternatively, something people will wonder is "will my old demography code work" and/or "how do I translate to the new demography"; perhaps we can address that here?
4. In the ARG section, we might make a diagram showing something that's in the full ARG but not the minimal tree sequence, to make the distinction clear? As part (b) of Figure 5?
5. In Figure 7, the y-axis is on a log scale. And, maybe we should extend the x-axis to 100Mb?
6. Maybe "simulation interface" and "development model" should go *first*?
7. In "development model" we could give an example of how we test things, to make it clear that it's rigorous.
8. There's no discussion of when you need to do forwards simulation (selection, continuous space, etc); maybe this belongs in the Introduction?
9. Should we describe how the mutation simulation algorithm works? In an appendix?
10. I wonder if there's some descriptive figures we'd like to include, e.g. a conceptual one that shows simulating trees and then adding mutations (using the nice tskit svg drawing capability), or example trees simulated with and without multiple mergers. This could spice up the performance figures (which all look the same).

I'm happy to do some of these things, but thought I should make one issue instead of ten - but, maybe if others agree a thing should be done, it should be made a separate issue? I'm not sure how to deal with this.

**Comment by benjeffery** [comment]
> I'm happy to do some of these things, but thought I should make one issue instead of ten - but, maybe if others agree a thing should be done, it should be made a separate issue? I'm not sure how to deal with this.

I've activated discussions on this repo - maybe it makes sense to have issues be "concrete changes or deliverables" and discussions be more open-ended?
