### ISSUE TITLE
ARG illustration

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#85]
From #83:

> In the ARG section, we might make a diagram showing something that's in the full ARG but not the minimal tree sequence, to make the distinction clear? As part (b) of Figure 5?

This sounds like an excellent idea to me. How about something  like this? 

![Screenshot from 2021-07-23 10-11-19](https://user-images.githubusercontent.com/2664569/126761371-9cb39e6a-4bbc-4990-b28d-b5f62e35f518.png)

This would make a good two panel figure then I think, (a) illustrating an ARG and the full-arg representation in msprime, and (b) showing how the extra ARG nodes come to dominate in large simulations.

Perhaps we could also show the simplified, minimal tree sequence too?

Any thoughts @JereKoskela?

**Comment by JereKoskela** [comment]
Looks great to me. I think including the simplified tree sequence would make sense if we have space for it - it makes for another good illustration of why the ARG comes with so much overhead.

**Comment by jeromekelleher** [comment]
After #120 goes in, the figure looks like this:

![Screenshot from 2021-08-09 17-30-48](https://user-images.githubusercontent.com/2664569/128741032-13013f99-3287-4d95-98e9-d15992d06d68.png)

We need to fix it up in some way. Probably the simplest thing to do would be to import the tree sequence SVG diagrams into inkscape (or whatever) and redo the ARG diagram. We've had some discussions in #89 about going the other direction and using tikz, but that's probably more work since the tikz isn't in the main library. That said, if I end up doing it myself I probably would use the tikz version, purely because I'm useless with inkscape (or any other drawing program).

Thoughts? Volunteers??

**Comment by gtsambos** [comment]
I can do it in tikz, hang on

**Comment by daniel-goldstein** [comment]
I personally find the plot helpful, as the asymptotic behavior is surprising to me only looking at the example. But I do think it's odd to put them all on one line, since it makes the plot look tacked on and the figure otherwise reads left to right. I'm not quite sure how best to arrange it but it reads more to me like two subfigures.

**Comment by jeromekelleher** [comment]
@daniel-goldstein - can you have another read through of the text please (it's just been updated)? I was hoping that the O(rho^2) vs O(rho) distinction would be pretty clear, and make any plot redundant.

**Comment by daniel-goldstein** [comment]
Quite clear. And the figure looks great @gtsambos!
