### ISSUE TITLE
Feature section: DTWF

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#9]
We need a feature section for DTWF. See #7 for an overview of feature section structures.

Are there other backwards time, generation by generation simulators we should be citing here?

@DomNelson, can you pick this one up please?

**Comment by DomNelson** [comment]
Yep sounds good. I only know of ARGON for backwards-time, would be great to know of any others.

**Comment by jeromekelleher** [comment]
I think there's:

- SIMCOAL/SIMCOAL 2, Serial SimCoal
- GENOME

See refs 28-31 in the 2016 msprime paper.

**Comment by jeromekelleher** [comment]
Closing - we have drafts of the various components in place.
