### ISSUE TITLE
runtime scaling of dtwf?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime-1.0-paper#91]
In #88, [@sgravel said](https://github.com/tskit-dev/msprime-1.0-paper/pull/88#issuecomment-885932143) that dtwf scales like `O(Ne^2 L)` instead of `O(Ne^2 L^2)`; currently there's no discussion of this. Should we add this? Is it discussed in the DTWF paper? Empirically, from that paper DTWF doesn't get faster than Hudson until quite long genomes (like, 30 Morgans, IIRC), so I think we may have decided this isn't a point we want to get into right now, since it'll be confusing in practice.

**Comment by jeromekelleher** [comment]
I think we should probably stay out of this one - our DTWF implementation has clear room for improvement (no reason we should be slower than ARGON), so I wouldn't try to make any predictions about its performance.
