### ISSUE TITLE
Change Appendix to Methods?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#93]
At the moment the Appendix is a list of "how we do stuff for X". We could change this to a Methods section instead?

I don't have a strong opinion, just putting the idea out there.

**Comment by petrelharp** [comment]
Good idea. But, let's see - right now the paper is 18 pages, plus 12 pages of references (!!!) and seven pages of appendix. So, this would push it to 25 pages. I guess I vote to keep it appendix-ey.

**Comment by jeromekelleher** [comment]
No one has piped up on this, so closing.
