### ISSUE TITLE
Hudson's algorithm time complexity

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime-1.0-paper#96]
There's been a bit of discussion on this, so I want to get the pieces together. Here's a plot from the 2016 paper:

![pcbi 1004842 g002](https://user-images.githubusercontent.com/2664569/127634479-3713cc20-2b6c-4004-93ee-eb57ff5ef0f5.png)

The dots on the left are a fitted quadratic. I used this to conjecture that Hudson is quadratic in rho - which the HSW bound confirms - we think it should be O(rho^2 log^2 n).

What would we want to do to check if the number of events really is well characterised by this expression? Would fitting it jointly to all the data here be convincing?

**Comment by jeromekelleher** [comment]
Here's the plots we currently have:

![ancestry-perf](https://user-images.githubusercontent.com/2664569/127635227-95f1af44-f84a-4132-898b-fe94359965b9.png)

![ancestry-perf-expected](https://user-images.githubusercontent.com/2664569/127634965-6923acf3-5c16-4f3e-b52f-87fb0b0a0f23.png)

The first one shows that we can fit quadratics to the actual running time, at different scales, and helps us predict what the actual run time will be for various scales.

The second shows that there's a strong correlation between the predictions of HSW bound and observed values, but that this correlation isn't particulary strong when rho is small (unsurprisingly).

**Comment by jeromekelleher** [comment]
So, I think we have the elements of a convincing story here, but too many plots. Would adding a third sample size value to the observed times plots, and jointly fitting a rho^2 log^2 n model be convincing?

I'm not convinced the separate "small rho" plot is that useful, and maybe putting some annotations on the big values would be more useful. For example, we could annotate the x-axis with the approximate genome sizes for a few organisms, say "human chr20" and a couple of others. Then maybe use this model to extrapolate out to how long it would take for a Drosophila chr in the text?

I don't find the observed-by-expected time plots all that helpful (or at least, not worth the space in the final paper; I really can't be bothered with supplemental figures). How about we say in the text "we get a correlation coefficient of xxx between the predictions of the HSW bound and observed timings for the data in figure X"? The behaviour at small rho isn't really interesting - we know the bound only applies in the large rho case, and anyway, measuring CPU times for these short runs are going to be affected by all sorts of other uninteresting things.

**Comment by jeromekelleher** [comment]
Ping @petrelharp and @sgravel for thoughts?

**Comment by jeromekelleher** [comment]
Hmm, my enthusiasm for the HSW bound has diminished a bit - it's a pretty poor predictor of the total number of recombination events, based on the data above:

![Screenshot from 2021-07-30 11-57-48](https://user-images.githubusercontent.com/2664569/127643575-1bbababd-d0be-41c1-b7a9-99052f182b8c.png)

So, I think we can really just say that run time is quadratic in rho, and weakly depends on n, but the exact relationship isn't really known. 

Data is [here](https://github.com/jeromekelleher/msprime-paper/blob/master/data/alg_stats.dat) in json format if anyone is interested in playing with it. I tried a lot of things to find a good predictor for the number of events at the time, so I don't think there's much point in spending time on it other than to day that the HSW bound confirms that fitting a quadratic for a given sample size is a reasonable thing to do.

**Comment by jeromekelleher** [comment]
My take on this now is that we shouldn't make any claims about how well the HSW bound predicts performance, but just say that it provides good justification for fitting a quadratic for a given sample size. It's not a very tight bound (it's massively larger than the actual number of events if you plot it), and it doesn't predict run time any better than rho^2 log n. I spend ages fiddling around trying to find a good predictor for n in the last paper, and didn't come up with anything, so I don't really want to spend any more time on it.

Saying we can predict run time well for a long genome by fitting a quadratic for shorter genome is what we started out wanting to do here; we have a theoretical justification for this now via the HSW bound, and I think we should be happy with that.

@petrelharp?

**Comment by petrelharp** [comment]
Hm, ok. Here's my take: from my experiments, the `log^2(n)` didn't start to predict things until about rho=40,000 or so, which is where your experiments ended (so, I'd try to fit something to *only* the points above rho=40,000). So, maybe it is a good predictor, but only for very big simulations, which is maybe not very useful. The best way I can think of to make this point is with the observed/expected vs rho plot above - but, it's a confusing point and a confusing figure, I agree. I don't mind removing it, or putting it back in the appendix. I think probably better practical advice is to say that do your timing experiments at the sample size you're aiming for, don't try to extrapolate *that*.

> I'm not convinced the separate "small rho" plot is that useful, 

The point of that figure was supposed to be to show what's possible in seconds - people *do* often just want to simulate a megabase lots of times, so this gives them an idea of how fast that'll be.

So, how about: scale back discussion of HSW, remove the second two figures, give a more nuanced discussion of how to predict runtimes (fix sample size, vary rho but don't try to extrapolate over too many orders of magnitude)?

**Comment by jeromekelleher** [comment]
> So, how about: scale back discussion of HSW, remove the second two figures, give a more nuanced discussion of how to predict runtimes (fix sample size, vary rho but don't try to extrapolate over too many orders of magnitude)?

Great, that's exactly what I was thinking. I think putting in a few annotations for different genome sizes would be helpful too.

**Comment by gregorgorjanc** [comment]
> > So, how about: scale back discussion of HSW, remove the second two figures, give a more nuanced discussion of how to predict runtimes (fix sample size, vary rho but don't try to extrapolate over too many orders of magnitude)?
> 
> Great, that's exactly what I was thinking. I think putting in a few annotations for different genome sizes would be helpful too.

For example, Drosophila is fine, but does not really have that large chromosomes. We should add an example/annotation for ~1 Morgan chromosomes - that's quite common chromosome size in mammals. I need to get to that cattle case at https://github.com/tskit-dev/msprime/issues/1651 - what time line are we looking with this manuscript @jeromekelleher ?

**Comment by jeromekelleher** [comment]
I think we need to be up front about the limitations that we've hit @gregorgorjanc. My plan is to annotate the two plots that Peter generated with a points corresponding to some species. We can then mention some others, extrapolating out how long it would take. Then we say "Until we have implemented the required approximations to the full coalescent with recombination in msprime, we recommend users who need to simulate moderate sample sizes for chromosomes with rho > SOME NUMBER use scrm"

Do you have some recommendations for useful species to consider here @gregorgorjanc (or better, numbers for rho?)

**Comment by petrelharp** [comment]
It was my (vague) understanding that in nearly all species chromosomes were not longer than a few morgans (regardless of their length in bp); is this not correct?

Annotation is a great idea: I really wanted to have the axis in something like bp, but since it's really rho it depends on I had to change it...

**Comment by petrelharp** [comment]
>  need to get to that cattle case at tskit-dev/msprime#1651 - what time line are we looking with this manuscript?

It's feeling nearly done - a week or so for substantial edits?

**Comment by jeromekelleher** [comment]
Yep, that's the timeline I'm working with. Really want to get this preprinted and submitted ASAP.

**Comment by petrelharp** [comment]
I'll have a go at doing these edits now.

**Comment by gregorgorjanc** [comment]
> It was my (vague) understanding that in nearly all species chromosomes were not longer than a few morgans (regardless of their length in bp); is this not correct?
> 
> Annotation is a great idea: I really wanted to have the axis in something like bp, but since it's really rho it depends on I had to change it...

Yes, correct! As long as 1 Morgan chromosomes are mentioned I am happy!

**Comment by gregorgorjanc** [comment]
> Do you have some recommendations for useful species to consider here @gregorgorjanc (or better, numbers for rho?)

Human with ~1 Morgan and N_e of ~10K (though that’s a bit nebulous number)

Ag species are roughly in that range - maize has ~2 Morgan chromosomes and cattle ~1 Morgan

I am not that familiar with other species, say Drosophila - it has smaller physical size, but we are talking genetic (recombination) size here - I agree with @petrelharp that genetic size is quite constant (for example human and cattle have ~3Gbp genome with ~30 Morgans, while honeybees have much smaller physical size yet similar genetic size).

Maybe skip annotation of specific cases? To avoid pulling in “exactly” right values for different species. An option would be to pick species in https://stdpopsim.readthedocs.io/en/latest/catalog.html

**Comment by gregorgorjanc** [comment]
Thinking a bit more I think what tripped me in previous manuscript versions was text saying something like "large genomes, such as in Drosophila". We often talk about "large genomes", but we are not clear if we are talking about physical or genetic (recombination) size. @petrelharp showed rho values in the figure - all basing on genetic (recombination) size - so, since most genomes have quite similar genetic (recombination length), then maybe talking (annotating) about different species is not needed (they will vary mostly in N_e and less in L)? Maybe then points to annotate could be:

1 Morgan at N_e of 10
1 Morgan at N_e of 100
1 Morgan at N_e of 1,000
1 Morgan at N_e of 10,000
1 Morgan at N_e of 100,000

One thing that confuses me is that a physically large genome will get more marginal trees than a physically smaller genome for the same genetic (recombination) size. Will this impact runtime in any way? I think not due to the tree sequence data structure, right?

**Comment by jeromekelleher** [comment]
> One thing that confuses me is that a physically large genome will get more marginal trees than a physically smaller genome for the same genetic (recombination) size. Will this impact runtime in any way? I think not due to the tree sequence data structure, right?

I get confused by genetic size and physical size, but if just fix on thinking about rho (scaled recombination rate, 4NLr), then bigger rho means longer run times, and larger outputs. Run time scales with rho^2, and output tree sequence file size scales with rho. Does this help, or make it worse @gregorgorjanc?

**Comment by petrelharp** [comment]
> "large genomes, such as in Drosophila"

gee - we should have said "large population size", since Drosophila has a small genome.

> One thing that confuses me is that a physically large genome will get more marginal trees than a physically smaller genome for the same genetic (recombination) size.

Hm - maybe slightly, but only to the extent that different recombination points happen to fall in the same place on the smaller one?

I've made changes in #103; see what you think.

**Comment by gregorgorjanc** [comment]
> > One thing that confuses me is that a physically large genome will get more marginal trees than a physically smaller genome for the same genetic (recombination) size. Will this impact runtime in any way? I think not due to the tree sequence data structure, right?
> 
> I get confused by genetic size and physical size, but if just fix on thinking about rho (scaled recombination rate, 4NLr, where N is populations size, L is the physical length of the genome in base pairs and r is the per generation recombination rate per base pair), then bigger rho means longer run times, and larger outputs. Run time scales with rho^2, and output tree sequence file size scales with rho. Does this help, or make it worse @gregorgorjanc?

It does help! Just to note that Lr is genetic size and this is what @petrelharp wrote about in the text. The way he wrote it makes it clear how genetic and physical size come into play.

@jeromekelleher do you want to mention the tree sequence file size scales linearly with rho? Or is this already in the PLoS paper?

**Comment by jeromekelleher** [comment]
We should mention this all right @gregorgorjanc - I'll make a pass through this morning and try to get the remaining missing things in (some species will be slow, use scrm; and how does the size of the output scale.)

**Comment by jeromekelleher** [comment]
Closed in #107 and #111.
